// PDF output contract — magic bytes, metadata, and content shape.
//
// #WAVE19-W10: Wave-19 spec asks for "PDF/A-2b conformant" exports.
// pdfkit (the library #WAVE11-P1-EXPORT picked after the Puppeteer
// retreat) does NOT emit PDF/A out of the box — full PDF/A-2b would
// need an XMP metadata stream + embedded ICC color profile + a
// font-embedding pass. That's a larger swap (likely to a different
// library or a post-process step via Ghostscript) than fits in a
// closure PR.
//
// What this test pins TODAY:
//   1. Output starts with `%PDF-1.x` magic bytes (§7.5.2 ISO 32000-1).
//   2. The four required Info-dictionary entries (Title, Author,
//      Creator, Producer) are present — these are the same fields
//      PDF/A-2b §8.6 requires, just not (yet) inside an XMP stream.
//   3. Output ends with `%%EOF` (§7.5.5).
//   4. KPIs and tables render without throwing on edge cases.
//
// The PDF/A-2b XMP-metadata + ICC-profile gap is tracked in
// docs/qa-reports/wave19-pdf-a-followup.md so it doesn't get lost.

import { describe, it, expect, vi } from "vitest";
import { type PdfReport, renderStructuredPdfResponse } from "../../lib/pdf";

const sampleReport: PdfReport = {
  title: "Risk Register Q1 2026",
  subtitle: "Auto-generated by ARCTOS",
  orgName: "Meridian Holdings GmbH",
  generatedAt: new Date("2026-05-15T10:00:00Z"),
  sections: [
    {
      heading: "Top 10 Risks (by residual score)",
      paragraph:
        "The following risks exceed the organization's risk-appetite threshold.",
      kpis: [
        { label: "Total risks", value: 27 },
        { label: "Critical", value: 4, trend: "crit" },
        { label: "Treated", value: 18, trend: "ok" },
      ],
      table: {
        headers: ["ID", "Title", "Inh.", "Res.", "Owner"],
        rows: [
          ["RSK00000001", "Cross-tenant data leak", 12, 6, "L. Schneider"],
          ["RSK00000002", "Vendor concentration", 9, 9, "M. Braun"],
          ["RSK00000003", "DSGVO 72h breach overdue", 16, 8, null],
        ],
      },
      notes: [
        "Residual scores reflect the most recent assessment as of 2026-05-15.",
      ],
    },
  ],
};

async function bufFromResponse(res: Response): Promise<Uint8Array> {
  const arr = await res.arrayBuffer();
  return new Uint8Array(arr);
}

describe("PDF output contract (Wave-19-W10)", () => {
  it("emits a 200 with content-type application/pdf", async () => {
    const res = await renderStructuredPdfResponse(
      sampleReport,
      "risk-register",
    );
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("application/pdf");
  });

  it("starts with %PDF- magic bytes (ISO 32000-1 §7.5.2)", async () => {
    const res = await renderStructuredPdfResponse(
      sampleReport,
      "risk-register",
    );
    const buf = await bufFromResponse(res);
    // Magic = '%' '%' 'P' 'D' 'F' '-' = 25 25 50 44 46 2D ... actually
    // it's '%' 'P' 'D' 'F' '-' = 25 50 44 46 2D in 5 bytes.
    expect(buf[0]).toBe(0x25); // %
    expect(buf[1]).toBe(0x50); // P
    expect(buf[2]).toBe(0x44); // D
    expect(buf[3]).toBe(0x46); // F
    expect(buf[4]).toBe(0x2d); // -
  });

  it("ends with %%EOF marker (ISO 32000-1 §7.5.5)", async () => {
    const res = await renderStructuredPdfResponse(
      sampleReport,
      "risk-register",
    );
    const buf = await bufFromResponse(res);
    // Decode the last ~8 bytes as ASCII; PDFs may end with '\n' or '\r\n'
    // after the marker.
    const tail = new TextDecoder().decode(buf.slice(buf.length - 16));
    expect(tail).toContain("%%EOF");
  });

  it("Info dictionary contains Title + Author + Creator + Producer", async () => {
    const res = await renderStructuredPdfResponse(
      sampleReport,
      "risk-register",
    );
    const buf = await bufFromResponse(res);
    // pdfkit writes the Info-dictionary keys with VALUES that may be
    // either inline literals `/Title (Risk Register…)` or indirect
    // references to a string object `/Title 18 0 R`. Either form is
    // valid PDF (§7.3.10 ISO 32000-1). We only assert the key is
    // present and the literal value appears somewhere in the stream.
    const text = new TextDecoder("latin1").decode(buf);
    expect(text).toMatch(/\/Title\s+(\(|\d+\s+\d+\s+R)/);
    expect(text).toMatch(/\/Author\s+(\(|\d+\s+\d+\s+R)/);
    expect(text).toMatch(/\/Creator\s+(\(|\d+\s+\d+\s+R)/);
    expect(text).toMatch(/\/Producer\s+(\(|\d+\s+\d+\s+R)/);
    // The Title we passed is 'Risk Register Q1 2026' — verify the actual
    // value made it into the file (in whichever object it landed).
    expect(text).toContain("Risk Register Q1 2026");
    // Author is the orgName we passed.
    expect(text).toContain("Meridian Holdings");
    // Creator is the static "ARCTOS GRC Platform" string set in
    // packages/web/src/lib/pdf.ts.
    expect(text).toContain("ARCTOS");
  });

  it("renders without error when KPI list is empty", async () => {
    const r: PdfReport = {
      ...sampleReport,
      sections: [{ heading: "Empty section", paragraph: "Nothing here." }],
    };
    const res = await renderStructuredPdfResponse(r, "empty-report");
    expect(res.status).toBe(200);
  });

  it("renders without error when a row contains a null cell", async () => {
    // The third row in sampleReport has `null` in the owner column.
    const res = await renderStructuredPdfResponse(sampleReport, "with-nulls");
    expect(res.status).toBe(200);
    const buf = await bufFromResponse(res);
    expect(buf.length).toBeGreaterThan(500); // valid PDFs are at least this big
  });

  it("filename is sanitized: special chars stripped from Content-Disposition", async () => {
    // The renderer's safeBase regex strips anything outside [a-zA-Z0-9-_].
    // Confirm a hostile filename can't break the header. (The `;` and
    // ` ` separator chars are part of the standard
    // `attachment; filename="..."` syntax — we only assert the FILENAME
    // portion is sanitized.)
    const res = await renderStructuredPdfResponse(
      sampleReport,
      "../../../etc/passwd; rm -rf /",
    );
    const cd = res.headers.get("content-disposition") ?? "";
    const fnMatch = cd.match(/filename="([^"]+)"/);
    expect(fnMatch).not.toBeNull();
    const fn = fnMatch![1];
    expect(fn).not.toContain("..");
    expect(fn).not.toContain("/");
    expect(fn).not.toContain(";");
    expect(fn).not.toContain(" ");
    expect(fn).toMatch(/^[a-zA-Z0-9_\-.]+\.pdf$/);
  });
});

// ─────────────────────────────────────────────────────────────────
// Failure branch of renderStructuredPdfResponse.
//
// The eight tests above all take the success path; the `catch` was
// uncovered, which is how the response could quote the underlying error
// message unnoticed. It is not a stack trace and the callers are
// authenticated — but it can name internals (file paths, library
// frames), and an authenticated tenant user has no use for them.
//
// Forcing the failure without mocking pdfkit: `renderStructuredPdfBuffer`
// is called directly inside the module, so spying on the module export
// would not intercept the call. A property getter that throws when the
// title is read fails inside that function's own try/catch and rejects
// the promise — the same shape as a corrupt-input failure, and it pins
// no pdfkit internals.
// ─────────────────────────────────────────────────────────────────

describe("PDF failure branch", () => {
  const SECRET_DETAIL =
    "ENOENT: no such file or directory, open '/srv/arctos/fonts/Helvetica.afm'";

  const throwingReport: PdfReport = {
    get title(): string {
      throw new Error(SECRET_DETAIL);
    },
    sections: [],
  };

  it("returns a 503 problem+json that does not echo the error message", async () => {
    // `@/lib/logger` writes to `process.stderr` in the Node runtime
    // (console is only the Edge fallback), so that is what we capture.
    const written: string[] = [];
    const stderrWrite = vi
      .spyOn(process.stderr, "write")
      .mockImplementation((chunk: unknown) => {
        written.push(String(chunk));
        return true;
      });
    try {
      const res = await renderStructuredPdfResponse(throwingReport, "boom");

      expect(res.status).toBe(503);
      expect(res.headers.get("content-type")).toBe(
        "application/problem+json; charset=utf-8",
      );

      const body = (await res.json()) as {
        type: string;
        title: string;
        status: number;
        detail: string;
      };
      expect(body.type).toBe(
        "https://arctos.charliehund.de/errors/pdf-render-failed",
      );
      expect(body.title).toBe("PDF generation failed");
      expect(body.status).toBe(503);

      const serialised = JSON.stringify(body);
      expect(serialised).not.toContain("ENOENT");
      expect(serialised).not.toContain("/srv/arctos/fonts");
      expect(serialised).not.toContain("Helvetica.afm");

      // The operator side loses nothing: the full message is logged,
      // tagged with the component that produced it.
      const logged = written.join("\n");
      expect(logged).toContain('"component":"pdf"');
      expect(logged).toContain("ENOENT");
      expect(logged).toContain("Helvetica.afm");
    } finally {
      stderrWrite.mockRestore();
    }
  });
});
