-- Sprint 63: Cloud Infrastructure Connectors
-- Migration 944: Seed GCP test definitions (15 tests)

INSERT INTO connector_test_definition (test_key, connector_type, provider_key, name, description, category, severity, framework_mappings, test_logic) VALUES
  ('gcp_iam_service_account_keys', 'gcp', 'gcp_iam', 'Service Account Key Rotation', 'Service account keys rotated within 90 days', 'iam', 'high', '[{"framework":"ISO27001","controlId":"A.9.2.4"}]', '{"apiCalls":["iam.serviceAccountKeys.list"],"evaluationRules":[{"field":"keyAgeDays","op":"<","value":90}]}'),
  ('gcp_iam_admin_sa', 'gcp', 'gcp_iam', 'Service Account Admin Privilege', 'No service accounts with admin roles', 'access_control', 'critical', '[]', '{"apiCalls":["iam.roles.list","resourcemanager.projects.getIamPolicy"],"evaluationRules":[{"field":"adminServiceAccounts","op":"=","value":0}]}'),
  ('gcp_iam_mfa', 'gcp', 'gcp_iam', 'MFA Enforcement', 'MFA enforced for all users', 'iam', 'critical', '[{"framework":"ISO27001","controlId":"A.9.4.2"}]', '{"apiCalls":["admin.users.list"],"evaluationRules":[{"field":"mfaEnrolled","op":"=","value":true}]}'),
  ('gcp_storage_public', 'gcp', 'gcp_storage', 'Storage Bucket Public Access', 'No publicly accessible storage buckets', 'data_protection', 'critical', '[]', '{"apiCalls":["storage.buckets.list","storage.buckets.getIamPolicy"],"evaluationRules":[{"field":"publicAccess","op":"=","value":false}]}'),
  ('gcp_storage_encryption', 'gcp', 'gcp_storage', 'Storage CMEK Encryption', 'Storage buckets use customer-managed encryption keys', 'encryption', 'high', '[{"framework":"ISO27001","controlId":"A.10.1.1"}]', '{"apiCalls":["storage.buckets.list"],"evaluationRules":[{"field":"cmekEnabled","op":"=","value":true}]}'),
  ('gcp_storage_uniform_access', 'gcp', 'gcp_storage', 'Uniform Bucket Access', 'Uniform bucket-level access enabled', 'access_control', 'medium', '[]', '{"apiCalls":["storage.buckets.list"],"evaluationRules":[{"field":"uniformAccess","op":"=","value":true}]}'),
  ('gcp_compute_disk_encryption', 'gcp', 'gcp_compute', 'Compute Disk Encryption', 'All compute disks encrypted with CMEK', 'encryption', 'high', '[]', '{"apiCalls":["compute.disks.list"],"evaluationRules":[{"field":"cmekEncrypted","op":"=","value":true}]}'),
  ('gcp_compute_serial_port', 'gcp', 'gcp_compute', 'Serial Port Disabled', 'Serial port access disabled on instances', 'configuration', 'medium', '[]', '{"apiCalls":["compute.instances.list"],"evaluationRules":[{"field":"serialPortDisabled","op":"=","value":true}]}'),
  ('gcp_firewall_ssh', 'gcp', 'gcp_compute', 'Firewall SSH Restricted', 'No firewall rules allow SSH from 0.0.0.0/0', 'network', 'critical', '[{"framework":"ISO27001","controlId":"A.13.1.1"}]', '{"apiCalls":["compute.firewalls.list"],"evaluationRules":[{"field":"unrestrictedSSH","op":"=","value":false}]}'),
  ('gcp_audit_logging', 'gcp', 'gcp_logging', 'Audit Logging Enabled', 'Cloud Audit Logs enabled for all services', 'logging', 'high', '[{"framework":"ISO27001","controlId":"A.12.4.1"}]', '{"apiCalls":["resourcemanager.projects.getIamPolicy"],"evaluationRules":[{"field":"auditLogsEnabled","op":"=","value":true}]}'),
  ('gcp_log_sink', 'gcp', 'gcp_logging', 'Log Export Sink', 'Log sinks configured for long-term retention', 'logging', 'high', '[]', '{"apiCalls":["logging.sinks.list"],"evaluationRules":[{"field":"sinksConfigured","op":">","value":0}]}'),
  ('gcp_sql_public', 'gcp', 'gcp_sql', 'Cloud SQL Public IP', 'No Cloud SQL instances have public IPs', 'network', 'critical', '[]', '{"apiCalls":["sqladmin.instances.list"],"evaluationRules":[{"field":"publicIp","op":"=","value":false}]}'),
  ('gcp_sql_ssl', 'gcp', 'gcp_sql', 'Cloud SQL SSL Required', 'Cloud SQL instances require SSL connections', 'encryption', 'high', '[]', '{"apiCalls":["sqladmin.instances.list"],"evaluationRules":[{"field":"sslRequired","op":"=","value":true}]}'),
  ('gcp_gke_private', 'gcp', 'gcp_gke', 'GKE Private Cluster', 'GKE clusters use private nodes', 'network', 'high', '[]', '{"apiCalls":["container.clusters.list"],"evaluationRules":[{"field":"privateNodes","op":"=","value":true}]}'),
  ('gcp_dns_dnssec', 'gcp', 'gcp_dns', 'DNSSEC Enabled', 'DNSSEC enabled for managed zones', 'network', 'medium', '[]', '{"apiCalls":["dns.managedZones.list"],"evaluationRules":[{"field":"dnssecEnabled","op":"=","value":true}]}')
ON CONFLICT (test_key) DO NOTHING;
