import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as platform from "./schema/platform";
import * as risk from "./schema/risk";
import * as processSchema from "./schema/process";
import * as taskSchema from "./schema/task";
import * as moduleSchema from "./schema/module";
import * as assetSchema from "./schema/asset";
import * as workItemSchema from "./schema/work-item";
import * as controlSchema from "./schema/control";
import * as documentSchema from "./schema/document";
import * as catalogSchema from "./schema/catalog";
import * as ismsSchema from "./schema/isms";
import * as bcmsSchema from "./schema/bcms";
import * as dpmsSchema from "./schema/dpms";
import * as auditMgmtSchema from "./schema/audit-mgmt";
import * as tprmSchema from "./schema/tprm";
import * as supplierPortalSchema from "./schema/supplier-portal";
import * as esgSchema from "./schema/esg";
import * as intelligenceSchema from "./schema/intelligence";
import * as whistleblowingSchema from "./schema/whistleblowing";
import * as budgetSchema from "./schema/budget";
import * as brandingSchema from "./schema/branding";
import * as rcsaSchema from "./schema/rcsa";
import * as policyAcknowledgmentSchema from "./schema/policy-acknowledgment";
import * as playbookSchema from "./schema/playbook";
import * as calendarSchema from "./schema/calendar";
import * as dashboardSchema from "./schema/dashboard";
import * as importExportSchema from "./schema/import-export";
import * as identitySchema from "./schema/identity";
import * as translationSchema from "./schema/translation";
import * as eventBusSchema from "./schema/event-bus";
import * as boardKpiSchema from "./schema/board-kpi";
import * as nis2CertificationSchema from "./schema/nis2-certification";
import * as fairSchema from "./schema/fair";
import * as ismsIntelligenceSchema from "./schema/isms-intelligence";
import * as complianceCultureSchema from "./schema/compliance-culture";
import * as automationSchema from "./schema/automation";
import * as reportingSchema from "./schema/reporting";
import * as regulatorySimulatorSchema from "./schema/regulatory-simulator";
import * as riskPropagationSchema from "./schema/risk-propagation";
import * as auditAnalyticsSchema from "./schema/audit-analytics";
import * as abacSchema from "./schema/abac";
import * as agentsSchema from "./schema/agents";
import * as eamSchema from "./schema/eam";
import * as eamAdvancedSchema from "./schema/eam-advanced";
import * as platformAdvancedSchema from "./schema/platform-advanced";
import * as ermAdvancedSchema from "./schema/erm-advanced";
import * as icsAdvancedSchema from "./schema/ics-advanced";
import * as bcmsAdvancedSchema from "./schema/bcms-advanced";
import * as dpmsAdvancedSchema from "./schema/dpms-advanced";
import * as auditAdvancedSchema from "./schema/audit-advanced";
import * as tprmAdvancedSchema from "./schema/tprm-advanced";
import * as esgAdvancedSchema from "./schema/esg-advanced";
import * as whistleblowingAdvancedSchema from "./schema/whistleblowing-advanced";
import * as bpmAdvancedSchema from "./schema/bpm-advanced";
import * as eamDashboardsSchema from "./schema/eam-dashboards";
import * as eamDataArchitectureSchema from "./schema/eam-data-architecture";
import * as eamAiSchema from "./schema/eam-ai";
import * as eamCatalogSchema from "./schema/eam-catalog";
import * as eamGovernanceSchema from "./schema/eam-governance";

const client = postgres(process.env.DATABASE_URL!);
export const db = drizzle(client, {
  schema: { ...platform, ...risk, ...processSchema, ...taskSchema, ...moduleSchema, ...assetSchema, ...workItemSchema, ...controlSchema, ...documentSchema, ...catalogSchema, ...ismsSchema, ...bcmsSchema, ...dpmsSchema, ...auditMgmtSchema, ...tprmSchema, ...supplierPortalSchema, ...esgSchema, ...intelligenceSchema, ...whistleblowingSchema, ...budgetSchema, ...brandingSchema, ...rcsaSchema, ...policyAcknowledgmentSchema, ...playbookSchema, ...calendarSchema, ...dashboardSchema, ...importExportSchema, ...identitySchema, ...translationSchema, ...eventBusSchema, ...boardKpiSchema, ...nis2CertificationSchema, ...fairSchema, ...ismsIntelligenceSchema, ...complianceCultureSchema, ...automationSchema, ...reportingSchema, ...regulatorySimulatorSchema, ...riskPropagationSchema, ...auditAnalyticsSchema, ...abacSchema, ...agentsSchema, ...eamSchema, ...eamAdvancedSchema, ...platformAdvancedSchema, ...ermAdvancedSchema, ...icsAdvancedSchema, ...bcmsAdvancedSchema, ...dpmsAdvancedSchema, ...auditAdvancedSchema, ...tprmAdvancedSchema, ...esgAdvancedSchema, ...whistleblowingAdvancedSchema, ...bpmAdvancedSchema, ...eamDashboardsSchema, ...eamDataArchitectureSchema, ...eamAiSchema, ...eamCatalogSchema, ...eamGovernanceSchema },
});

export type Database = typeof db;
export * from "./schema/platform";
export * from "./schema/risk";
export * from "./schema/process";
export * from "./schema/task";
export * from "./schema/module";
export * from "./schema/asset";
export * from "./schema/work-item";
export * from "./schema/control";
export * from "./schema/document";
export * from "./schema/catalog";
export * from "./schema/isms";
export * from "./schema/bcms";
export * from "./schema/dpms";
export * from "./schema/audit-mgmt";
export * from "./schema/tprm";
export * from "./schema/supplier-portal";
export * from "./schema/esg";
export * from "./schema/intelligence";
export * from "./schema/whistleblowing";
export * from "./schema/budget";
export * from "./schema/branding";
export * from "./schema/rcsa";
export * from "./schema/policy-acknowledgment";
export * from "./schema/playbook";
export * from "./schema/calendar";
export * from "./schema/dashboard";
export * from "./schema/import-export";
export * from "./schema/identity";
export * from "./schema/translation";
export * from "./schema/event-bus";
export * from "./schema/board-kpi";
export * from "./schema/nis2-certification";
export * from "./schema/fair";
export * from "./schema/isms-intelligence";
export * from "./schema/compliance-culture";
export * from "./schema/automation";
export * from "./schema/reporting";
export * from "./schema/regulatory-simulator";
export * from "./schema/risk-propagation";
export * from "./schema/audit-analytics";
export * from "./schema/abac";
export * from "./schema/agents";
export * from "./schema/eam";
export * from "./schema/eam-advanced";
export * from "./schema/platform-advanced";
export * from "./schema/erm-advanced";
export * from "./schema/ics-advanced";
export * from "./schema/bcms-advanced";
export * from "./schema/dpms-advanced";
export * from "./schema/audit-advanced";
export * from "./schema/tprm-advanced";
export * from "./schema/esg-advanced";
export * from "./schema/whistleblowing-advanced";
export * from "./schema/bpm-advanced";
export * from "./schema/eam-dashboards";
export * from "./schema/eam-data-architecture";
export * from "./schema/eam-ai";
export * from "./schema/eam-catalog";
export * from "./schema/eam-governance";
