import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as platform from "./schema/platform";
import * as risk from "./schema/risk";
import * as processSchema from "./schema/process";
import * as taskSchema from "./schema/task";
import * as moduleSchema from "./schema/module";
import * as assetSchema from "./schema/asset";
import * as workItemSchema from "./schema/work-item";
import * as controlSchema from "./schema/control";
import * as documentSchema from "./schema/document";
import * as catalogSchema from "./schema/catalog";
import * as ismsSchema from "./schema/isms";
import * as bcmsSchema from "./schema/bcms";
import * as dpmsSchema from "./schema/dpms";
import * as auditMgmtSchema from "./schema/audit-mgmt";
import * as tprmSchema from "./schema/tprm";
import * as supplierPortalSchema from "./schema/supplier-portal";
import * as esgSchema from "./schema/esg";
import * as intelligenceSchema from "./schema/intelligence";
import * as whistleblowingSchema from "./schema/whistleblowing";
import * as budgetSchema from "./schema/budget";
import * as brandingSchema from "./schema/branding";
import * as rcsaSchema from "./schema/rcsa";
import * as policyAcknowledgmentSchema from "./schema/policy-acknowledgment";
import * as playbookSchema from "./schema/playbook";
import * as calendarSchema from "./schema/calendar";
import * as dashboardSchema from "./schema/dashboard";
import * as importExportSchema from "./schema/import-export";
import * as identitySchema from "./schema/identity";
import * as translationSchema from "./schema/translation";
import * as eventBusSchema from "./schema/event-bus";
import * as boardKpiSchema from "./schema/board-kpi";

const client = postgres(process.env.DATABASE_URL!);
export const db = drizzle(client, {
  schema: { ...platform, ...risk, ...processSchema, ...taskSchema, ...moduleSchema, ...assetSchema, ...workItemSchema, ...controlSchema, ...documentSchema, ...catalogSchema, ...ismsSchema, ...bcmsSchema, ...dpmsSchema, ...auditMgmtSchema, ...tprmSchema, ...supplierPortalSchema, ...esgSchema, ...intelligenceSchema, ...whistleblowingSchema, ...budgetSchema, ...brandingSchema, ...rcsaSchema, ...policyAcknowledgmentSchema, ...playbookSchema, ...calendarSchema, ...dashboardSchema, ...importExportSchema, ...identitySchema, ...translationSchema, ...eventBusSchema, ...boardKpiSchema },
});

export type Database = typeof db;
export * from "./schema/platform";
export * from "./schema/risk";
export * from "./schema/process";
export * from "./schema/task";
export * from "./schema/module";
export * from "./schema/asset";
export * from "./schema/work-item";
export * from "./schema/control";
export * from "./schema/document";
export * from "./schema/catalog";
export * from "./schema/isms";
export * from "./schema/bcms";
export * from "./schema/dpms";
export * from "./schema/audit-mgmt";
export * from "./schema/tprm";
export * from "./schema/supplier-portal";
export * from "./schema/esg";
export * from "./schema/intelligence";
export * from "./schema/whistleblowing";
export * from "./schema/budget";
export * from "./schema/branding";
export * from "./schema/rcsa";
export * from "./schema/policy-acknowledgment";
export * from "./schema/playbook";
export * from "./schema/calendar";
export * from "./schema/dashboard";
export * from "./schema/import-export";
export * from "./schema/identity";
export * from "./schema/translation";
export * from "./schema/event-bus";
export * from "./schema/board-kpi";
