#!/bin/bash
# ============================================================================
# ARCTOS — Stelle sicher, dass jeder Tenant einen Worker-Service hat
#
# Idempotent: prüft pro Tenant ob worker-<name> in docker-compose.yml
# definiert ist. Wenn nicht: regeneriert die docker-compose.yml mit web +
# worker (preserved den Host-Port aus der bestehenden Datei).
#
# Wird vom update-all.sh aufgerufen, kann auch standalone laufen:
#   sudo bash /opt/arctos/deploy/ensure-tenant-worker.sh
# ============================================================================

set -euo pipefail

TENANTS_DIR="/opt/arctos/tenants"

if [ ! -d "$TENANTS_DIR" ]; then
  echo "Keine Tenants vorhanden ($TENANTS_DIR fehlt) — nichts zu tun."
  exit 0
fi

UPDATED_COUNT=0
SKIPPED_COUNT=0

for tdir in "$TENANTS_DIR"/*/; do
  [ -d "$tdir" ] || continue
  TENANT=$(basename "$tdir")
  COMPOSE="$tdir/docker-compose.yml"

  if [ ! -f "$COMPOSE" ]; then
    echo "  $TENANT: docker-compose.yml fehlt — übersprungen"
    SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
    continue
  fi

  if grep -q "^  worker-$TENANT:" "$COMPOSE"; then
    SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
    continue
  fi

  # Bestehenden Host-Port extrahieren — wir wollen ihn nicht ändern.
  # Format in der bestehenden Datei: '      - "127.0.0.1:3010:3000"'
  HOST_PORT=$(grep -oP '127\.0\.0\.1:\K[0-9]+' "$COMPOSE" | head -1)
  if [ -z "$HOST_PORT" ]; then
    echo "  $TENANT: konnte Host-Port nicht aus $COMPOSE lesen — übersprungen"
    SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
    continue
  fi

  echo "  $TENANT: ergänze Worker-Service (port=$HOST_PORT für web)"

  # Backup der alten Datei (einmalig, nicht überschreiben)
  if [ ! -f "$COMPOSE.pre-worker-backup" ]; then
    cp "$COMPOSE" "$COMPOSE.pre-worker-backup"
  fi

  cat > "$COMPOSE" <<DCEOF
# ============================================================================
# Tenant: $TENANT
#
# Two services per tenant:
#   - web-$TENANT     : Next.js app, exposed on host port $HOST_PORT
#   - worker-$TENANT  : Cron engine (Hono), tenant-isolated DATABASE_URL,
#                       CRON_SECRET, WB_ENCRYPTION_KEY from ./env
#
# Tenant isolation guarantees:
#   - Each tenant has its own process — a compromised cron handler in
#     tenant A cannot reach tenant B's data.
#   - Each tenant has its own CRON_SECRET → tenant A operators cannot
#     trigger tenant B's crons even with shell access to the same host.
#   - DATABASE_URL is per-tenant; the worker can ONLY see its own DB.
#
# Auto-generated by ensure-tenant-worker.sh; preserved port: $HOST_PORT
# ============================================================================

services:
  web-$TENANT:
    image: ghcr.io/arctos/grc-web:latest
    build:
      context: /opt/arctos
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:$HOST_PORT:3000"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - env
    networks:
      - arctos_arctos

  worker-$TENANT:
    build:
      context: /opt/arctos
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - env
    environment:
      PORT: "3001"
    networks:
      - arctos_arctos

networks:
  arctos_arctos:
    external: true
DCEOF

  UPDATED_COUNT=$((UPDATED_COUNT + 1))
done

echo "  ensure-tenant-worker: $UPDATED_COUNT aktualisiert, $SKIPPED_COUNT bereits ok"
