export {
  DEFAULT_CCI_WEIGHTS,
  CCI_FACTOR_KEYS,
  normalizeFactor,
  normalizeFactors,
  calculateWeightedCCI,
  detectTrend,
  calcPercentageScore,
  calcIncidentResponseScore,
  validateWeights,
  buildCCIResult,
  getPeriodString,
  getPreviousPeriod,
  getPeriodRange,
  getTopImprovementAreas,
} from "./calculator";
