-- Sprint 63: Cloud Infrastructure Connectors
-- Migration 943: Seed Azure test definitions (25 tests)

INSERT INTO connector_test_definition (test_key, connector_type, provider_key, name, description, category, severity, framework_mappings, test_logic) VALUES
  ('azure_ad_mfa_all_users', 'azure', 'azure_ad', 'MFA for All Users', 'MFA enabled for all users via Conditional Access', 'iam', 'critical', '[{"framework":"ISO27001","controlId":"A.9.4.2"}]', '{"apiCalls":["graph:conditionalAccess/policies"],"evaluationRules":[{"field":"mfaEnforced","op":"=","value":true}]}'),
  ('azure_ad_legacy_auth', 'azure', 'azure_ad', 'Block Legacy Authentication', 'Legacy authentication protocols blocked', 'iam', 'high', '[]', '{"apiCalls":["graph:conditionalAccess/policies"],"evaluationRules":[{"field":"legacyAuthBlocked","op":"=","value":true}]}'),
  ('azure_ad_privileged_roles', 'azure', 'azure_ad', 'Privileged Role Assignment', 'Limited Global Admin assignments', 'access_control', 'critical', '[{"framework":"ISO27001","controlId":"A.9.2.3"}]', '{"apiCalls":["graph:directoryRoles"],"evaluationRules":[{"field":"globalAdminCount","op":"<=","value":5}]}'),
  ('azure_ad_guest_access', 'azure', 'azure_ad', 'Guest Access Restrictions', 'Guest user access properly restricted', 'access_control', 'medium', '[]', '{"apiCalls":["graph:policies/authorizationPolicy"],"evaluationRules":[{"field":"guestAccessRestricted","op":"=","value":true}]}'),
  ('azure_ad_password_protection', 'azure', 'azure_ad', 'Password Protection', 'Custom banned password list enabled', 'iam', 'high', '[]', '{"apiCalls":["graph:settings"],"evaluationRules":[{"field":"passwordProtectionEnabled","op":"=","value":true}]}'),
  ('azure_storage_encryption', 'azure', 'azure_storage', 'Storage Account Encryption', 'Storage accounts use customer-managed keys', 'encryption', 'high', '[{"framework":"ISO27001","controlId":"A.10.1.1"}]', '{"apiCalls":["storage:list"],"evaluationRules":[{"field":"encryptionEnabled","op":"=","value":true}]}'),
  ('azure_storage_public_access', 'azure', 'azure_storage', 'Storage Public Access', 'No storage accounts allow public blob access', 'data_protection', 'critical', '[]', '{"apiCalls":["storage:list"],"evaluationRules":[{"field":"publicAccess","op":"=","value":false}]}'),
  ('azure_storage_https', 'azure', 'azure_storage', 'Storage HTTPS Only', 'Storage accounts enforce HTTPS transfer', 'encryption', 'high', '[]', '{"apiCalls":["storage:list"],"evaluationRules":[{"field":"httpsOnly","op":"=","value":true}]}'),
  ('azure_keyvault_soft_delete', 'azure', 'azure_keyvault', 'Key Vault Soft Delete', 'Key Vaults have soft delete enabled', 'encryption', 'high', '[]', '{"apiCalls":["keyvault:list"],"evaluationRules":[{"field":"softDeleteEnabled","op":"=","value":true}]}'),
  ('azure_keyvault_purge_protection', 'azure', 'azure_keyvault', 'Key Vault Purge Protection', 'Key Vaults have purge protection enabled', 'encryption', 'high', '[]', '{"apiCalls":["keyvault:list"],"evaluationRules":[{"field":"purgeProtection","op":"=","value":true}]}'),
  ('azure_nsg_ssh_restricted', 'azure', 'azure_network', 'NSG SSH Restricted', 'No NSGs allow unrestricted SSH from internet', 'network', 'critical', '[{"framework":"ISO27001","controlId":"A.13.1.1"}]', '{"apiCalls":["network:nsg/list"],"evaluationRules":[{"field":"unrestrictedSSH","op":"=","value":false}]}'),
  ('azure_nsg_rdp_restricted', 'azure', 'azure_network', 'NSG RDP Restricted', 'No NSGs allow unrestricted RDP from internet', 'network', 'critical', '[]', '{"apiCalls":["network:nsg/list"],"evaluationRules":[{"field":"unrestrictedRDP","op":"=","value":false}]}'),
  ('azure_sql_encryption', 'azure', 'azure_sql', 'SQL TDE Enabled', 'Transparent Data Encryption on all SQL databases', 'encryption', 'high', '[]', '{"apiCalls":["sql:servers/list","sql:databases/list"],"evaluationRules":[{"field":"tdeEnabled","op":"=","value":true}]}'),
  ('azure_sql_auditing', 'azure', 'azure_sql', 'SQL Auditing Enabled', 'SQL Server auditing enabled', 'logging', 'high', '[{"framework":"ISO27001","controlId":"A.12.4.1"}]', '{"apiCalls":["sql:servers/auditingSettings"],"evaluationRules":[{"field":"auditingEnabled","op":"=","value":true}]}'),
  ('azure_sql_firewall', 'azure', 'azure_sql', 'SQL Firewall Rules', 'No SQL servers allow all Azure IPs', 'network', 'high', '[]', '{"apiCalls":["sql:servers/firewallRules"],"evaluationRules":[{"field":"allowAllAzureIps","op":"=","value":false}]}'),
  ('azure_vm_disk_encryption', 'azure', 'azure_compute', 'VM Disk Encryption', 'All VM disks encrypted', 'encryption', 'high', '[]', '{"apiCalls":["compute:disks/list"],"evaluationRules":[{"field":"encryptionEnabled","op":"=","value":true}]}'),
  ('azure_vm_extensions', 'azure', 'azure_compute', 'VM Security Extensions', 'Endpoint protection extensions installed', 'monitoring', 'medium', '[]', '{"apiCalls":["compute:virtualMachines/list"],"evaluationRules":[{"field":"endpointProtection","op":"=","value":true}]}'),
  ('azure_activity_log', 'azure', 'azure_monitor', 'Activity Log Retention', 'Activity logs retained for at least 90 days', 'logging', 'high', '[]', '{"apiCalls":["monitor:activityLogAlerts/list"],"evaluationRules":[{"field":"retentionDays","op":">=","value":90}]}'),
  ('azure_diagnostic_settings', 'azure', 'azure_monitor', 'Diagnostic Settings', 'Diagnostic settings enabled for key services', 'logging', 'medium', '[]', '{"apiCalls":["monitor:diagnosticSettings/list"],"evaluationRules":[{"field":"diagnosticsEnabled","op":"=","value":true}]}'),
  ('azure_security_center', 'azure', 'azure_security', 'Defender for Cloud', 'Defender for Cloud standard tier enabled', 'monitoring', 'high', '[]', '{"apiCalls":["security:pricings/list"],"evaluationRules":[{"field":"standardTier","op":"=","value":true}]}'),
  ('azure_policy_assignments', 'azure', 'azure_policy', 'Policy Assignments', 'Azure Policy assignments configured', 'configuration', 'medium', '[]', '{"apiCalls":["policy:assignments/list"],"evaluationRules":[{"field":"assignmentCount","op":">","value":0}]}'),
  ('azure_webapp_https', 'azure', 'azure_webapp', 'Web App HTTPS Only', 'Web Apps enforce HTTPS', 'encryption', 'high', '[]', '{"apiCalls":["web:sites/list"],"evaluationRules":[{"field":"httpsOnly","op":"=","value":true}]}'),
  ('azure_webapp_tls', 'azure', 'azure_webapp', 'Web App TLS Version', 'Web Apps use TLS 1.2 or higher', 'encryption', 'high', '[]', '{"apiCalls":["web:sites/config"],"evaluationRules":[{"field":"minTlsVersion","op":">=","value":"1.2"}]}'),
  ('azure_aks_rbac', 'azure', 'azure_aks', 'AKS RBAC Enabled', 'AKS clusters have RBAC enabled', 'access_control', 'high', '[]', '{"apiCalls":["containerservice:managedClusters/list"],"evaluationRules":[{"field":"rbacEnabled","op":"=","value":true}]}'),
  ('azure_container_registry', 'azure', 'azure_acr', 'ACR Content Trust', 'Container Registry content trust enabled', 'configuration', 'medium', '[]', '{"apiCalls":["containerregistry:registries/list"],"evaluationRules":[{"field":"contentTrust","op":"=","value":true}]}')
ON CONFLICT (test_key) DO NOTHING;
