-- Sprint 64: Identity und SaaS Connectors
-- Migration 949: Seed identity and SaaS test definitions

INSERT INTO connector_test_definition (test_key, connector_type, provider_key, name, description, category, severity, framework_mappings, test_logic) VALUES
  ('entra_mfa_enforcement', 'entra_id', 'entra_id', 'Entra ID MFA Enforcement', 'All users have MFA enforced via Conditional Access', 'iam', 'critical', '[{"framework":"ISO27001","controlId":"A.9.4.2"}]', '{"apiCalls":["graph:users","graph:conditionalAccess"],"evaluationRules":[{"field":"mfaEnforced","op":"=","value":true}]}'),
  ('entra_stale_accounts', 'entra_id', 'entra_id', 'Stale Account Detection', 'Detect accounts not signed in for configured period', 'access_control', 'high', '[{"framework":"ISO27001","controlId":"A.9.2.6"}]', '{"apiCalls":["graph:users?$select=signInActivity"],"evaluationRules":[{"field":"lastSignInDays","op":"<","value":90}]}'),
  ('entra_access_reviews', 'entra_id', 'entra_id', 'Access Reviews Active', 'Access reviews configured and completing on schedule', 'access_control', 'high', '[]', '{"apiCalls":["graph:identityGovernance/accessReviews"],"evaluationRules":[{"field":"activeReviews","op":">","value":0}]}'),
  ('entra_privileged_pim', 'entra_id', 'entra_id', 'PIM for Privileged Roles', 'Privileged Identity Management enabled for admin roles', 'access_control', 'critical', '[]', '{"apiCalls":["graph:privilegedAccess"],"evaluationRules":[{"field":"pimEnabled","op":"=","value":true}]}'),
  ('entra_conditional_access', 'entra_id', 'entra_id', 'Conditional Access Policies', 'Key conditional access policies are active', 'access_control', 'high', '[]', '{"apiCalls":["graph:conditionalAccess/policies"],"evaluationRules":[{"field":"activePolicies","op":">=","value":3}]}'),
  ('gws_mfa_enforcement', 'google_workspace', 'google_workspace', 'Google Workspace MFA', 'MFA enforced for all users', 'iam', 'critical', '[]', '{"apiCalls":["admin:users"],"evaluationRules":[{"field":"mfaEnforced","op":"=","value":true}]}'),
  ('gws_external_sharing', 'google_workspace', 'google_workspace', 'Drive External Sharing', 'External file sharing properly restricted', 'data_protection', 'high', '[]', '{"apiCalls":["admin:reports"],"evaluationRules":[{"field":"externalSharingRestricted","op":"=","value":true}]}'),
  ('gws_admin_accounts', 'google_workspace', 'google_workspace', 'Super Admin Count', 'Limited number of super admin accounts', 'access_control', 'critical', '[]', '{"apiCalls":["admin:users?query=isAdmin=true"],"evaluationRules":[{"field":"superAdminCount","op":"<=","value":5}]}'),
  ('m365_dlp_policies', 'm365', 'm365', 'M365 DLP Policies', 'Data Loss Prevention policies configured and active', 'data_protection', 'high', '[{"framework":"ISO27001","controlId":"A.8.2.3"}]', '{"apiCalls":["compliance:dlpPolicies"],"evaluationRules":[{"field":"activePolicies","op":">","value":0}]}'),
  ('m365_retention_policies', 'm365', 'm365', 'M365 Retention Policies', 'Retention policies configured for compliance', 'data_protection', 'high', '[]', '{"apiCalls":["compliance:retentionPolicies"],"evaluationRules":[{"field":"activePolicies","op":">","value":0}]}'),
  ('m365_sensitivity_labels', 'm365', 'm365', 'Sensitivity Labels', 'Sensitivity labels published and in use', 'data_protection', 'medium', '[]', '{"apiCalls":["compliance:sensitivityLabels"],"evaluationRules":[{"field":"publishedLabels","op":">","value":0}]}'),
  ('m365_mailbox_audit', 'm365', 'm365', 'Mailbox Audit Logging', 'Mailbox audit logging enabled for all mailboxes', 'logging', 'high', '[]', '{"apiCalls":["exchange:mailboxAuditBypass"],"evaluationRules":[{"field":"auditEnabled","op":"=","value":true}]}'),
  ('hr_onboarding_sla', 'hr_system', 'hr_system', 'Onboarding SLA Compliance', 'New employee IT provisioning within SLA', 'access_control', 'medium', '[]', '{"apiCalls":["hr:onboarding/pending"],"evaluationRules":[{"field":"slaMet","op":"=","value":true}]}'),
  ('hr_offboarding_sla', 'hr_system', 'hr_system', 'Offboarding SLA Compliance', 'Departing employee IT deprovisioning within SLA', 'access_control', 'high', '[{"framework":"ISO27001","controlId":"A.9.2.6"}]', '{"apiCalls":["hr:offboarding/pending"],"evaluationRules":[{"field":"slaMet","op":"=","value":true}]}')
ON CONFLICT (test_key) DO NOTHING;
