-- Sprint 65: DevOps und IT Connectors
-- Migration 954: Seed DevOps and IT test definitions

INSERT INTO connector_test_definition (test_key, connector_type, provider_key, name, description, category, severity, framework_mappings, test_logic) VALUES
  ('git_branch_protection', 'git_platform', 'git_platform', 'Branch Protection Rules', 'Main branch has required reviews and status checks', 'access_control', 'high', '[{"framework":"ISO27001","controlId":"A.14.2.2"}]', '{"apiCalls":["repos/branches/protection"],"evaluationRules":[{"field":"protectionEnabled","op":"=","value":true}]}'),
  ('git_code_review_coverage', 'git_platform', 'git_platform', 'Code Review Coverage', 'All merged PRs have at least one approval', 'access_control', 'high', '[]', '{"apiCalls":["repos/pulls?state=closed"],"evaluationRules":[{"field":"reviewCoverage","op":">=","value":95}]}'),
  ('git_sast_enabled', 'git_platform', 'git_platform', 'SAST Pipeline Enabled', 'Static analysis security testing in CI pipeline', 'configuration', 'high', '[]', '{"apiCalls":["repos/actions/workflows"],"evaluationRules":[{"field":"sastEnabled","op":"=","value":true}]}'),
  ('git_secret_scanning', 'git_platform', 'git_platform', 'Secret Scanning Active', 'Secret scanning alerts enabled and monitored', 'data_protection', 'critical', '[]', '{"apiCalls":["repos/secret-scanning/alerts"],"evaluationRules":[{"field":"secretScanningEnabled","op":"=","value":true}]}'),
  ('git_signed_commits', 'git_platform', 'git_platform', 'Signed Commits Required', 'Commit signing required on protected branches', 'access_control', 'medium', '[]', '{"apiCalls":["repos/branches/protection"],"evaluationRules":[{"field":"requireSignedCommits","op":"=","value":true}]}'),
  ('git_dependency_scanning', 'git_platform', 'git_platform', 'Dependency Vulnerability Scanning', 'Dependabot or similar enabled for vulnerability alerts', 'configuration', 'high', '[]', '{"apiCalls":["repos/vulnerability-alerts"],"evaluationRules":[{"field":"vulnAlertsEnabled","op":"=","value":true}]}'),
  ('issue_sla_response', 'issue_tracker', 'issue_tracker', 'Issue Response SLA', 'Issues responded to within SLA timeframe', 'configuration', 'medium', '[]', '{"apiCalls":["search/issues"],"evaluationRules":[{"field":"slaResponseMet","op":">=","value":90}]}'),
  ('issue_sla_resolution', 'issue_tracker', 'issue_tracker', 'Issue Resolution SLA', 'Issues resolved within SLA timeframe', 'configuration', 'medium', '[]', '{"apiCalls":["search/issues"],"evaluationRules":[{"field":"slaResolutionMet","op":">=","value":85}]}'),
  ('wiki_docs_freshness', 'wiki', 'wiki', 'Documentation Freshness', 'Critical documents updated within threshold', 'configuration', 'medium', '[]', '{"apiCalls":["content/search"],"evaluationRules":[{"field":"staleDocsPercent","op":"<","value":20}]}'),
  ('endpoint_encryption', 'endpoint_mgmt', 'endpoint_mgmt', 'Endpoint Disk Encryption', 'All managed endpoints have disk encryption', 'encryption', 'high', '[{"framework":"ISO27001","controlId":"A.10.1.1"}]', '{"apiCalls":["devices/list"],"evaluationRules":[{"field":"encryptionEnabled","op":"=","value":true}]}'),
  ('endpoint_patching', 'endpoint_mgmt', 'endpoint_mgmt', 'Endpoint Patch Compliance', 'All endpoints patched within SLA', 'configuration', 'high', '[]', '{"apiCalls":["devices/compliance"],"evaluationRules":[{"field":"patchCompliance","op":">=","value":95}]}'),
  ('endpoint_antivirus', 'endpoint_mgmt', 'endpoint_mgmt', 'Endpoint Antivirus Status', 'Antivirus/EDR active and current on all endpoints', 'monitoring', 'high', '[]', '{"apiCalls":["devices/protection"],"evaluationRules":[{"field":"avActive","op":"=","value":true}]}'),
  ('firewall_rule_review', 'network_firewall', 'network_firewall', 'Firewall Rule Review', 'Firewall rules reviewed within policy period', 'network', 'high', '[{"framework":"ISO27001","controlId":"A.13.1.1"}]', '{"apiCalls":["firewall/rules"],"evaluationRules":[{"field":"rulesReviewedPercent","op":">=","value":90}]}'),
  ('firewall_any_any_rules', 'network_firewall', 'network_firewall', 'No Any-Any Rules', 'No overly permissive any-any firewall rules', 'network', 'critical', '[]', '{"apiCalls":["firewall/rules"],"evaluationRules":[{"field":"anyAnyRules","op":"=","value":0}]}')
ON CONFLICT (test_key) DO NOTHING;
