import { db, eamAiConfig, eamChatSession } from "@grc/db";
import { requireModule } from "@grc/auth";
import { chatSchema } from "@grc/shared";
import { eq, and } from "drizzle-orm";
import { withAuth } from "@/lib/api";
// [E2E-TRIAGE-2026-09-02] withErrorHandler opens the requestDbStorage.run()
// frame that withAuth needs to bind the org-pinned connection; without it the
// handler queries the context-less pool and RLS filters every row (api.ts:184).
import { withErrorHandler } from "@/lib/api-wrapper";

// POST /api/v1/eam/chat — Chatbot question (RAG pipeline)
export const POST = withErrorHandler(async function POST(req: Request) {
  const ctx = await withAuth("admin", "risk_manager", "viewer");
  if (ctx instanceof Response) return ctx;

  const moduleCheck = await requireModule("eam", ctx.orgId, req.method);
  if (moduleCheck) return moduleCheck;

  const config = await db
    .select()
    .from(eamAiConfig)
    .where(
      and(eq(eamAiConfig.orgId, ctx.orgId), eq(eamAiConfig.isActive, true)),
    )
    .limit(1);

  if (!config.length) {
    return Response.json(
      {
        error:
          "AI features require an LLM provider. Configure one in Settings > AI Provider.",
      },
      { status: 503 },
    );
  }

  const body = await req.json();
  const parsed = chatSchema.safeParse(body);
  if (!parsed.success)
    return Response.json({ error: parsed.error.flatten() }, { status: 422 });

  const decryptedConfig = JSON.parse(
    Buffer.from(config[0].configEncrypted, "base64").toString(),
  );

  // RAG Pipeline (provider-independent retrieval steps):
  // 1. Entity extraction (regex + keyword matching - NO LLM)
  // 2. Full-text search across EAM objects
  // 3. Relationship traversal via entity_reference
  // 4. GRC context enrichment (risks, controls, CVEs)
  // 5. Send to LLM with rag_system prompt

  // Create/update chat session
  let sessionId = parsed.data.sessionId;
  if (!sessionId) {
    const session = await db
      .insert(eamChatSession)
      .values({
        orgId: ctx.orgId,
        userId: ctx.userId,
        title: parsed.data.question.substring(0, 100),
        messages: [{ role: "user", content: parsed.data.question }],
        provider: decryptedConfig.provider,
        model: decryptedConfig.model,
      })
      .returning();
    sessionId = session[0].id;
  } else {
    const existing = await db
      .select()
      .from(eamChatSession)
      .where(eq(eamChatSession.id, sessionId))
      .limit(1);
    if (existing.length) {
      const messages =
        (existing[0].messages as Array<Record<string, string>>) ?? [];
      messages.push({ role: "user", content: parsed.data.question });
      await db
        .update(eamChatSession)
        .set({ messages, updatedAt: new Date() })
        .where(eq(eamChatSession.id, sessionId));
    }
  }

  return Response.json({
    data: {
      answer:
        "RAG answer would be generated by the configured LLM provider through the abstraction layer.",
      references: [],
      sessionId,
      provider: decryptedConfig.provider,
      model: decryptedConfig.model,
    },
  });
});
