-- ============================================================================
-- ARCTOS Seed: EU Cyber Resilience Act (Regulation (EU) 2024/2847)
-- Source: Regulation (EU) 2024/2847 — text adopted 2024-11-23
--
-- Structure: Annex I sets out essential cybersecurity requirements for
-- products with digital elements. Annex II covers vulnerability handling.
-- Annex III lists important products (Class I + II) under stricter regime.
--
-- Compliance becomes applicable in stages from 2026; full applicability 2027.
-- Target modules: isms (product-side IS), ics (controls), tprm (component supply chain)
-- ============================================================================

INSERT INTO catalog (id, name, description, catalog_type, scope, source, version, language, is_active, target_modules)
VALUES (
  'c0000000-0000-0000-0000-c8c2024c2024',
  'EU Cyber Resilience Act (CRA, 2024/2847)',
  'EU Cyber Resilience Act: horizontal cybersecurity requirements for products with digital elements (PDE). Annex I essential requirements + Annex II vulnerability handling. Mandatory CE-marking for all PDE in EU market from 2027.',
  'control', 'platform', 'eu_cra_2024', '2024/2847', 'en', true, '{isms,ics,tprm}'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO catalog_entry (catalog_id, code, name, name_de, description, description_de, level, sort_order, status) VALUES
-- ── Annex I, Part I — Essential cybersecurity requirements ─────────────────
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1', 'Annex I, Part I — Essential cybersecurity requirements relating to PDE', 'Annex I, Teil I — Wesentliche Cybersecurity-Anforderungen für PDE', 'Essential cybersecurity requirements that products with digital elements must meet', 'Wesentliche Cybersecurity-Anforderungen, die Produkte mit digitalen Elementen erfüllen müssen', 0, 100, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.1', 'Designed, developed and produced to ensure appropriate level of cybersecurity', 'Entwurf, Entwicklung und Produktion mit angemessenem Cybersecurity-Niveau', 'PDE shall be designed, developed and produced to ensure an appropriate level of cybersecurity based on the risks', 'PDE müssen so entworfen, entwickelt und produziert werden, dass ein risikobasiert angemessenes Cybersecurity-Niveau gewährleistet ist', 1, 101, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.2', 'Made available without known exploitable vulnerabilities', 'Bereitstellung ohne bekannte ausnutzbare Schwachstellen', 'PDE shall be made available on the market without any known exploitable vulnerabilities', 'PDE dürfen nicht mit bekannten ausnutzbaren Schwachstellen in den Verkehr gebracht werden', 1, 102, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.3', 'Secure by default configuration', 'Sicher voreingestellte Konfiguration', 'PDE shall be made available with a secure by default configuration; users shall have the possibility to reset to original state', 'PDE müssen mit einer sicheren Standardkonfiguration bereitgestellt werden; Nutzer müssen den Originalzustand wiederherstellen können', 1, 103, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.4', 'Protection from unauthorized access', 'Schutz vor unbefugtem Zugang', 'Ensure protection from unauthorized access by appropriate control mechanisms', 'Schutz vor unbefugtem Zugang durch angemessene Kontrollmechanismen sicherstellen', 1, 104, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.5', 'Protect confidentiality of stored, transmitted or processed data', 'Vertraulichkeit gespeicherter/übertragener/verarbeiteter Daten schützen', 'Protect confidentiality of stored, transmitted or otherwise processed data, personal or other (e.g. by encryption)', 'Vertraulichkeit gespeicherter, übertragener oder anderweitig verarbeiteter Daten (personenbezogen oder sonstige) schützen, z. B. durch Verschlüsselung', 1, 105, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.6', 'Protect integrity of data, commands, programs, configuration', 'Integrität von Daten, Befehlen, Programmen, Konfiguration schützen', 'Protect the integrity of stored, transmitted or otherwise processed data, commands, programs and configuration against any manipulation or modification not authorised by the user', 'Integrität gespeicherter/übertragener/verarbeiteter Daten, Befehle, Programme und Konfigurationen gegen unbefugte Manipulation/Änderung schützen', 1, 106, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.7', 'Process only data adequate, relevant and limited to product purpose', 'Datenminimierung gemäß Produktzweck', 'Process only data, personal or other, that are adequate, relevant and limited to what is necessary in relation to the intended purpose', 'Nur personenbezogene/andere Daten verarbeiten, die für den vorgesehenen Zweck angemessen, relevant und auf das Notwendige begrenzt sind', 1, 107, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.8', 'Protect availability of essential and basic functions', 'Verfügbarkeit wesentlicher und grundlegender Funktionen schützen', 'Protect the availability of essential and basic functions, also after an incident, including through resilience and mitigation measures against denial-of-service attacks', 'Verfügbarkeit wesentlicher und grundlegender Funktionen, auch nach einem Vorfall, durch Resilienz- und Minderungsmaßnahmen gegen DoS-Angriffe schützen', 1, 108, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.9', 'Minimise own negative impact on availability of services provided by other devices/networks', 'Negative Auswirkungen auf die Verfügbarkeit anderer Geräte/Netzwerke minimieren', 'Minimise their own negative impact on the availability of services provided by other devices or networks', 'Eigene negative Auswirkungen auf die Verfügbarkeit von Diensten anderer Geräte/Netzwerke minimieren', 1, 109, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.10', 'Limit attack surfaces, including external interfaces', 'Angriffsflächen begrenzen, inkl. externer Schnittstellen', 'Be designed, developed and produced to limit attack surfaces, including external interfaces', 'So entworfen/entwickelt/produziert werden, dass Angriffsflächen, inkl. externer Schnittstellen, begrenzt werden', 1, 110, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.11', 'Reduce impact of an incident using appropriate exploitation mitigation', 'Auswirkung eines Vorfalls durch geeignete Exploit-Minderung reduzieren', 'Be designed, developed and produced to reduce the impact of an incident using appropriate exploitation mitigation mechanisms and techniques', 'So entworfen/entwickelt/produziert werden, dass die Auswirkungen eines Vorfalls durch geeignete Exploit-Minderungs-Mechanismen reduziert werden', 1, 111, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.12', 'Provide security-related information by recording/monitoring relevant internal activity', 'Sicherheitsrelevante Informationen durch Aufzeichnung/Überwachung interner Aktivitäten bereitstellen', 'Provide security-related information by recording or monitoring relevant internal activity, including the access to or modification of data, services or functions, with an opt-out mechanism for the user', 'Sicherheitsrelevante Informationen durch Aufzeichnung/Überwachung relevanter interner Aktivitäten bereitstellen, mit Opt-out-Mechanismus für den Nutzer', 1, 112, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.1.13', 'Address vulnerabilities through security updates', 'Schwachstellen durch Sicherheitsupdates beheben', 'Provide the possibility to address vulnerabilities through security updates, including, where applicable, automatic updates that are installed within an appropriate time-frame and a clear and easy-to-use opt-out mechanism', 'Möglichkeit zur Behebung von Schwachstellen durch Sicherheitsupdates bieten, ggf. automatisch innerhalb eines angemessenen Zeitrahmens, mit klarem Opt-out', 1, 113, 'active'),

-- ── Annex I, Part II — Vulnerability handling requirements ─────────────────
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2', 'Annex I, Part II — Vulnerability handling requirements', 'Annex I, Teil II — Anforderungen an Schwachstellenbehandlung', 'Vulnerability handling processes that manufacturers must implement during the support period', 'Schwachstellenbehandlungs-Prozesse, die Hersteller während des Support-Zeitraums implementieren müssen', 0, 200, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.1', 'Identify and document vulnerabilities and components, including SBOM', 'Schwachstellen und Komponenten identifizieren und dokumentieren, inkl. SBOM', 'Identify and document vulnerabilities and components, including by drawing up a software bill of materials in a commonly used and machine-readable format covering at the very least the top-level dependencies of the products', 'Schwachstellen und Komponenten identifizieren und dokumentieren, inkl. SBOM in maschinenlesbarem Format, das mindestens die Top-Level-Abhängigkeiten abdeckt', 1, 201, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.2', 'Address and remediate vulnerabilities without delay', 'Schwachstellen unverzüglich behandeln und beheben', 'Address and remediate vulnerabilities without delay, including by providing security updates; where appropriate this can include automatic updates and end-user notification of available updates', 'Schwachstellen unverzüglich behandeln und beheben, einschließlich Sicherheitsupdates; ggf. automatische Updates und Endnutzer-Benachrichtigung', 1, 202, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.3', 'Apply effective and regular tests and reviews of security', 'Wirksame regelmäßige Tests und Sicherheitsüberprüfungen', 'Apply effective and regular tests and reviews of the security of the product with digital elements', 'Wirksame regelmäßige Tests und Sicherheitsüberprüfungen des Produkts durchführen', 1, 203, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.4', 'Share and publicly disclose information about fixed vulnerabilities', 'Informationen zu behobenen Schwachstellen teilen und veröffentlichen', 'Once a security update has been made available, share and publicly disclose information about fixed vulnerabilities', 'Nach Verfügbarkeit eines Sicherheitsupdates Informationen über behobene Schwachstellen teilen und veröffentlichen', 1, 204, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.5', 'Coordinated vulnerability disclosure policy', 'Richtlinie zur koordinierten Schwachstellenoffenlegung', 'Put in place and enforce a policy on coordinated vulnerability disclosure', 'Richtlinie zur koordinierten Schwachstellenoffenlegung etablieren und durchsetzen', 1, 205, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.6', 'Take measures to facilitate the sharing of information about potential vulnerabilities', 'Maßnahmen zur Erleichterung des Informationsaustauschs über mögliche Schwachstellen', 'Take measures to facilitate the sharing of information about potential vulnerabilities by providing a contact address', 'Maßnahmen zur Erleichterung des Austauschs über mögliche Schwachstellen ergreifen, durch Bereitstellung einer Kontaktadresse', 1, 206, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.7', 'Provide for mechanisms to securely distribute updates', 'Mechanismen für sichere Update-Verteilung', 'Provide for mechanisms to securely distribute updates for products with digital elements to ensure that exploitable vulnerabilities are fixed or mitigated in a timely manner and, where applicable for security updates, in an automatic manner', 'Mechanismen für die sichere Verteilung von Updates bereitstellen, um ausnutzbare Schwachstellen zeitnah zu beheben oder zu mindern; wo möglich automatisch', 1, 207, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'I.2.8', 'Ensure security updates are disseminated without delay and free of charge', 'Sicherheitsupdates unverzüglich und kostenlos verteilen', 'Ensure that, where security updates are available to address identified security issues, they are disseminated without delay and, unless otherwise agreed in respect of bespoke products, free of charge', 'Sicherstellen, dass verfügbare Sicherheitsupdates unverzüglich und (außer bei Sonderanfertigungen) kostenlos verteilt werden', 1, 208, 'active'),

-- ── Reporting obligations (Article 14) ─────────────────────────────────────
('c0000000-0000-0000-0000-c8c2024c2024', 'ART14', 'Article 14 — Reporting obligations of manufacturers', 'Artikel 14 — Meldepflichten der Hersteller', 'Notification of actively exploited vulnerabilities and severe incidents', 'Meldung aktiv ausgenutzter Schwachstellen und schwerer Vorfälle', 0, 300, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'ART14.1.a', 'Early warning of actively exploited vulnerability — within 24 hours', 'Frühwarnung aktiv ausgenutzter Schwachstelle — innerhalb 24 Stunden', 'Submit early warning notification to ENISA and the relevant CSIRT within 24 hours of becoming aware of an actively exploited vulnerability', 'Frühwarnung an ENISA und das zuständige CSIRT innerhalb von 24 Stunden nach Kenntnisnahme einer aktiv ausgenutzten Schwachstelle', 1, 310, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'ART14.1.b', 'Vulnerability notification — within 72 hours', 'Schwachstellenmeldung — innerhalb 72 Stunden', 'Submit vulnerability notification within 72 hours including affected product, corrective or mitigating measures', 'Schwachstellenmeldung innerhalb von 72 Stunden, inkl. betroffenes Produkt, Abhilfe- oder Minderungsmaßnahmen', 1, 320, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'ART14.1.c', 'Final report on vulnerability — within 14 days', 'Abschlussbericht zur Schwachstelle — innerhalb 14 Tagen', 'Submit final report within 14 days after security update is available, describing vulnerability, severity, root cause, mitigations and corrective measures', 'Abschlussbericht innerhalb von 14 Tagen nach Verfügbarkeit des Updates, mit Schwachstellenbeschreibung, Schweregrad, Root Cause, Minderung und Korrekturmaßnahmen', 1, 330, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'ART14.3.a', 'Severe incident — early warning within 24 hours', 'Schwerer Vorfall — Frühwarnung innerhalb 24 Stunden', 'Submit early warning of a severe incident having impact on security of the PDE within 24 hours', 'Frühwarnung eines schweren Vorfalls mit Auswirkung auf die Sicherheit des PDE innerhalb 24 Stunden', 1, 340, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'ART14.3.b', 'Severe incident notification — within 72 hours', 'Schwerer-Vorfall-Meldung — innerhalb 72 Stunden', 'Submit incident notification with general information on nature, affected products and any corrective measures within 72 hours', 'Vorfallmeldung mit allgemeinen Informationen zu Art, betroffenen Produkten und Korrekturmaßnahmen innerhalb 72 Stunden', 1, 350, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'ART14.3.c', 'Severe incident — final report within 14 days', 'Schwerer Vorfall — Abschlussbericht innerhalb 14 Tagen', 'Submit final report on the incident within 14 days after a corrective measure is available', 'Abschlussbericht zum Vorfall innerhalb von 14 Tagen nach Verfügbarkeit der Korrekturmaßnahme', 1, 360, 'active'),

-- ── Conformity Assessment + Documentation ─────────────────────────────────
('c0000000-0000-0000-0000-c8c2024c2024', 'CA', 'Conformity Assessment + CE-Marking', 'Konformitätsbewertung + CE-Kennzeichnung', 'Procedures and documentation required for placing PDE on the EU market', 'Verfahren und Dokumentation für das Inverkehrbringen von PDE im EU-Markt', 0, 400, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'CA.1', 'Risk assessment of the PDE', 'Risikobewertung des PDE', 'Conduct a cybersecurity risk assessment of the PDE and its intended use', 'Cybersecurity-Risikobewertung des PDE und seiner bestimmungsgemäßen Verwendung durchführen', 1, 410, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'CA.2', 'Technical documentation per Annex VII', 'Technische Dokumentation gem. Annex VII', 'Compile and maintain technical documentation as set out in Annex VII for at least 10 years after placing on market', 'Technische Dokumentation gemäß Annex VII erstellen und mindestens 10 Jahre nach Inverkehrbringen aufbewahren', 1, 420, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'CA.3', 'EU declaration of conformity', 'EU-Konformitätserklärung', 'Draw up the EU declaration of conformity per Annex V before placing the PDE on the market', 'EU-Konformitätserklärung gemäß Annex V vor Inverkehrbringen des PDE erstellen', 1, 430, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'CA.4', 'CE marking', 'CE-Kennzeichnung', 'Affix the CE marking visibly, legibly and indelibly to the PDE or, where that is not possible, to its packaging or accompanying documents', 'CE-Kennzeichnung sichtbar, lesbar und unauslöschlich am PDE anbringen oder, wenn nicht möglich, an Verpackung oder Begleitdokumenten', 1, 440, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'CA.5', 'Information and instructions to the user (Annex II)', 'Informationen und Anweisungen für den Nutzer (Annex II)', 'Provide information and instructions to the user as set out in Annex II', 'Informationen und Anweisungen für den Nutzer gemäß Annex II bereitstellen', 1, 450, 'active'),
('c0000000-0000-0000-0000-c8c2024c2024', 'CA.6', 'Support period', 'Support-Zeitraum', 'Determine and declare the support period during which security updates are provided (typically the expected lifetime of the product, with minimums)', 'Support-Zeitraum bestimmen und erklären, in dem Sicherheitsupdates bereitgestellt werden (üblicherweise die erwartete Produktlebensdauer mit Mindestwerten)', 1, 460, 'active')
ON CONFLICT (catalog_id, code) DO NOTHING;

-- Done. ~31 EU CRA entries (Annex I Parts I + II + Article 14 reporting + Conformity Assessment)
