-- ============================================================================
-- ARCTOS Seed: PCI DSS v4.0.1 — Payment Card Industry Data Security Standard
-- Source: PCI Security Standards Council, PCI DSS v4.0.1 (June 2024)
-- 12 requirements / 64 sub-requirements / 320+ controls
--
-- This seed includes the 12 top-level requirements plus the most-cited
-- sub-requirements (~50). Full text per PCI SSC license.
--
-- Target modules: isms, ics (any tenant processing card data)
-- ============================================================================

INSERT INTO catalog (id, name, description, catalog_type, scope, source, version, language, is_active, target_modules)
VALUES (
  'c0000000-0000-0000-0000-cd0040000001',
  'PCI DSS v4.0.1',
  'Payment Card Industry Data Security Standard v4.0.1: 12 requirements covering build-secure networks, protect cardholder data, vulnerability management, access control, monitoring and IS-policy.',
  'control', 'platform', 'pci_dss_v4', '4.0.1', 'en', true, '{isms,ics,dpms}'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO catalog_entry (catalog_id, code, name, name_de, description, description_de, level, sort_order, status) VALUES
-- ── Build and Maintain a Secure Network and Systems ────────────────────────
('c0000000-0000-0000-0000-cd0040000001', 'R1', 'Install and maintain network security controls', 'Netzwerk-Sicherheitsmaßnahmen installieren und pflegen', 'NSCs (firewalls/security groups) shall be installed and maintained to control traffic between trusted and untrusted networks.', 'NSCs (Firewalls/Security-Gruppen) müssen installiert und gepflegt werden, um den Verkehr zwischen vertrauenswürdigen und nicht-vertrauenswürdigen Netzwerken zu steuern.', 0, 100, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '1.2', 'NSC configuration standards defined and applied', 'NSC-Konfigurationsstandards', 'Configuration standards for NSCs shall be defined, implemented and maintained.', 'Konfigurationsstandards für NSCs müssen definiert, implementiert und gepflegt werden.', 1, 110, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '1.3', 'Network access to/from CDE restricted', 'Netzwerkzugriff von/zu CDE eingeschränkt', 'Network access to and from the cardholder data environment shall be restricted to that which is necessary.', 'Netzwerkzugriff von/zu der Karteninhaberdaten-Umgebung muss auf das Notwendige beschränkt sein.', 1, 120, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '1.4', 'Network connections between trusted and untrusted networks controlled', 'Netzwerkverbindungen zwischen vertrauenswürdigen und nicht-vertrauenswürdigen Netzwerken kontrolliert', 'Network connections between trusted and untrusted networks shall be controlled.', 'Netzwerkverbindungen zwischen vertrauenswürdigen und nicht-vertrauenswürdigen Netzwerken müssen kontrolliert werden.', 1, 130, 'active'),

('c0000000-0000-0000-0000-cd0040000001', 'R2', 'Apply secure configurations to all system components', 'Sichere Konfigurationen für alle Systemkomponenten', 'Secure configurations shall be developed, implemented and maintained for all system components.', 'Sichere Konfigurationen müssen für alle Systemkomponenten entwickelt, implementiert und gepflegt werden.', 0, 200, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '2.2', 'System components configured according to standards', 'Systemkomponenten gemäß Standards konfiguriert', 'System components shall be configured and managed securely.', 'Systemkomponenten müssen sicher konfiguriert und verwaltet werden.', 1, 210, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '2.3', 'Wireless environments configured securely', 'Wireless-Umgebungen sicher konfiguriert', 'Wireless environments shall be configured and managed securely.', 'Wireless-Umgebungen müssen sicher konfiguriert und verwaltet werden.', 1, 220, 'active'),

-- ── Protect Account Data ──────────────────────────────────────────────────
('c0000000-0000-0000-0000-cd0040000001', 'R3', 'Protect stored account data', 'Schutz gespeicherter Kontodaten', 'Stored account data shall be kept to a minimum and protected with cryptography.', 'Gespeicherte Kontodaten müssen minimiert und durch Kryptographie geschützt werden.', 0, 300, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '3.2', 'Storage of account data minimized', 'Speicherung von Kontodaten minimiert', 'Storage of account data shall be kept to a minimum.', 'Die Speicherung von Kontodaten muss auf das Minimum beschränkt werden.', 1, 310, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '3.3', 'Sensitive authentication data not stored after authorization', 'Sensible Authentifizierungsdaten nach Autorisierung nicht gespeichert', 'Sensitive authentication data (CVV, full track, PIN) shall not be stored after authorization.', 'Sensible Authentifizierungsdaten (CVV, vollständige Spur, PIN) dürfen nach Autorisierung nicht gespeichert werden.', 1, 320, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '3.4', 'Access to displays of full PAN restricted', 'Zugriff auf Anzeige der vollständigen PAN beschränkt', 'Access to displays of full PAN and the ability to copy account data shall be restricted.', 'Zugriff auf Anzeige der vollständigen PAN und das Kopieren von Kontodaten müssen eingeschränkt werden.', 1, 330, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '3.5', 'PAN secured wherever it is stored', 'PAN überall wo gespeichert gesichert', 'PAN shall be secured wherever it is stored (e.g., one-way hash, truncation, tokenization, strong cryptography).', 'PAN muss überall, wo sie gespeichert wird, gesichert werden (Einweg-Hash, Truncation, Tokenisierung, starke Kryptographie).', 1, 340, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '3.6', 'Cryptographic keys protected', 'Kryptographische Schlüssel geschützt', 'Cryptographic keys used to protect stored account data shall be secured.', 'Kryptographische Schlüssel zum Schutz gespeicherter Kontodaten müssen gesichert werden.', 1, 350, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '3.7', 'Where cryptography is used, processes are defined', 'Verfahren bei Einsatz von Kryptographie definiert', 'Cryptographic processes for protecting stored account data shall be defined and implemented.', 'Kryptographische Verfahren zum Schutz gespeicherter Kontodaten müssen definiert und implementiert werden.', 1, 360, 'active'),

('c0000000-0000-0000-0000-cd0040000001', 'R4', 'Protect cardholder data with strong cryptography during transmission', 'Schutz Karteninhaberdaten mit starker Kryptographie bei Übertragung', 'PAN shall be protected with strong cryptography during transmission over open, public networks.', 'PAN muss bei Übertragung über offene/öffentliche Netzwerke mit starker Kryptographie geschützt werden.', 0, 400, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '4.2', 'PAN protected with strong cryptography during transmission', 'PAN mit starker Kryptographie bei Übertragung geschützt', 'PAN transmitted over open, public networks shall be protected with strong cryptography.', 'Über offene/öffentliche Netzwerke übertragene PAN muss mit starker Kryptographie geschützt werden.', 1, 410, 'active'),

-- ── Maintain a Vulnerability Management Program ────────────────────────────
('c0000000-0000-0000-0000-cd0040000001', 'R5', 'Protect all systems and networks from malicious software', 'Schutz aller Systeme und Netzwerke vor Schadsoftware', 'Anti-malware mechanisms shall be deployed and maintained on all systems commonly affected by malware.', 'Anti-Malware-Mechanismen müssen auf allen üblicherweise von Malware betroffenen Systemen eingesetzt und gepflegt werden.', 0, 500, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '5.2', 'Malicious software prevented or detected', 'Schadsoftware verhindert oder erkannt', 'Anti-malware mechanisms shall be deployed on all system components.', 'Anti-Malware-Mechanismen müssen auf allen Systemkomponenten eingesetzt werden.', 1, 510, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '5.3', 'Anti-malware mechanisms active and updated', 'Anti-Malware-Mechanismen aktiv und aktualisiert', 'Anti-malware mechanisms shall be active, maintained and monitored.', 'Anti-Malware-Mechanismen müssen aktiv, gepflegt und überwacht werden.', 1, 520, 'active'),

('c0000000-0000-0000-0000-cd0040000001', 'R6', 'Develop and maintain secure systems and software', 'Sichere Systeme und Software entwickeln und pflegen', 'Bespoke and custom software shall be developed securely; vulnerabilities shall be patched.', 'Maßgeschneiderte/Custom-Software muss sicher entwickelt werden; Schwachstellen müssen gepatcht werden.', 0, 600, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '6.2', 'Bespoke and custom software developed securely', 'Bespoke/Custom-Software sicher entwickelt', 'Bespoke and custom software shall be developed securely.', 'Bespoke- und Custom-Software muss sicher entwickelt werden.', 1, 610, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '6.3', 'Security vulnerabilities identified and addressed', 'Sicherheitsschwachstellen identifiziert und behoben', 'Security vulnerabilities shall be identified and addressed.', 'Sicherheitsschwachstellen müssen identifiziert und behoben werden.', 1, 620, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '6.4', 'Public-facing web applications protected', 'Öffentlich zugängliche Webanwendungen geschützt', 'Public-facing web applications shall be protected against attacks.', 'Öffentlich zugängliche Webanwendungen müssen vor Angriffen geschützt werden.', 1, 630, 'active'),

-- ── Implement Strong Access Control Measures ───────────────────────────────
('c0000000-0000-0000-0000-cd0040000001', 'R7', 'Restrict access to system components and cardholder data by business need to know', 'Zugang zu Systemkomponenten und Karteninhaberdaten nach Need-to-Know einschränken', 'Access to system components and cardholder data shall be appropriately restricted.', 'Zugang zu Systemkomponenten und Karteninhaberdaten muss angemessen eingeschränkt werden.', 0, 700, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '7.2', 'Access to system components and data appropriately defined and assigned', 'Zugang zu Systemkomponenten und Daten angemessen definiert und zugewiesen', 'Access to system components and data shall be defined, assigned and managed.', 'Zugang zu Systemkomponenten und Daten muss definiert, zugewiesen und verwaltet werden.', 1, 710, 'active'),

('c0000000-0000-0000-0000-cd0040000001', 'R8', 'Identify users and authenticate access to system components', 'Benutzer identifizieren und Zugang zu Systemkomponenten authentifizieren', 'Identification and authentication shall be implemented for all access to system components.', 'Identifikation und Authentifizierung müssen für jeden Zugang zu Systemkomponenten implementiert werden.', 0, 800, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '8.2', 'User identification and related accounts strictly managed', 'Benutzeridentifikation und zugehörige Konten streng verwaltet', 'User identification and related accounts for users and administrators shall be strictly managed.', 'Benutzeridentifikation und zugehörige Konten für Benutzer und Administratoren müssen streng verwaltet werden.', 1, 810, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '8.3', 'Strong authentication for users and administrators', 'Starke Authentifizierung für Benutzer und Administratoren', 'Strong authentication for users and administrators shall be established and managed.', 'Starke Authentifizierung für Benutzer und Administratoren muss etabliert und verwaltet werden.', 1, 820, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '8.4', 'Multi-factor authentication implemented to secure access', 'MFA zur Sicherung des Zugangs implementiert', 'MFA shall be implemented to secure access into the CDE.', 'MFA muss zur Sicherung des CDE-Zugangs implementiert werden.', 1, 830, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '8.5', 'MFA systems configured to prevent misuse', 'MFA-Systeme zur Missbrauchsverhinderung konfiguriert', 'MFA systems shall be configured to prevent misuse.', 'MFA-Systeme müssen so konfiguriert werden, dass Missbrauch verhindert wird.', 1, 840, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '8.6', 'Use of application/system accounts and associated authentication factors strictly managed', 'Nutzung von Anwendungs-/Systemkonten und zugehörigen Faktoren streng verwaltet', 'Use of application and system accounts and associated authentication factors shall be strictly managed.', 'Die Nutzung von Anwendungs- und Systemkonten und zugehörigen Authentifizierungsfaktoren muss streng verwaltet werden.', 1, 850, 'active'),

('c0000000-0000-0000-0000-cd0040000001', 'R9', 'Restrict physical access to cardholder data', 'Physischen Zugang zu Karteninhaberdaten einschränken', 'Physical access to cardholder data and to systems containing cardholder data shall be restricted.', 'Physischer Zugang zu Karteninhaberdaten und Systemen, die diese enthalten, muss eingeschränkt werden.', 0, 900, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '9.2', 'Physical access controls manage entry into facilities and systems', 'Physische Zugangskontrollen für Einrichtungen und Systeme', 'Physical access controls shall manage entry into facilities and systems.', 'Physische Zugangskontrollen müssen den Zugang zu Einrichtungen und Systemen verwalten.', 1, 910, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '9.4', 'Media with cardholder data secured', 'Medien mit Karteninhaberdaten gesichert', 'Media with cardholder data shall be securely stored, accessed, distributed and destroyed.', 'Medien mit Karteninhaberdaten müssen sicher gespeichert, zugänglich gemacht, verteilt und vernichtet werden.', 1, 920, 'active'),

-- ── Regularly Monitor and Test Networks ────────────────────────────────────
('c0000000-0000-0000-0000-cd0040000001', 'R10', 'Log and monitor all access to system components and cardholder data', 'Alle Zugriffe auf Systemkomponenten und Karteninhaberdaten protokollieren und überwachen', 'Audit logs shall be implemented to support detection of anomalies and forensic investigations.', 'Audit-Logs müssen die Erkennung von Anomalien und forensische Untersuchungen unterstützen.', 0, 1000, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '10.2', 'Audit logs implemented to support detection of anomalies', 'Audit-Logs zur Erkennung von Anomalien implementiert', 'Audit logs shall be implemented to support the detection of anomalies and forensic investigations.', 'Audit-Logs müssen zur Erkennung von Anomalien und forensischen Untersuchungen implementiert werden.', 1, 1010, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '10.3', 'Audit logs protected from destruction and unauthorized modification', 'Audit-Logs vor Zerstörung und unbefugter Änderung geschützt', 'Audit logs shall be protected from destruction and unauthorized modification.', 'Audit-Logs müssen vor Zerstörung und unbefugter Änderung geschützt werden.', 1, 1020, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '10.4', 'Audit logs reviewed to identify anomalies and suspicious activity', 'Audit-Logs zur Erkennung von Anomalien und verdächtigen Aktivitäten überprüft', 'Audit logs shall be reviewed to identify anomalies or suspicious activity.', 'Audit-Logs müssen überprüft werden, um Anomalien oder verdächtige Aktivitäten zu erkennen.', 1, 1030, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '10.6', 'Time-synchronization mechanisms support consistent time settings across all systems', 'Zeitsynchronisations-Mechanismen für konsistente Zeit auf allen Systemen', 'Time-synchronization mechanisms shall support consistent time settings.', 'Zeitsynchronisations-Mechanismen müssen konsistente Zeiteinstellungen unterstützen.', 1, 1040, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '10.7', 'Failures of critical security control systems detected, reported and responded to promptly', 'Ausfälle kritischer Sicherheits-Controls zeitnah erkannt, gemeldet und behoben', 'Failures of critical security control systems shall be detected, reported and responded to promptly.', 'Ausfälle kritischer Sicherheits-Controls müssen zeitnah erkannt, gemeldet und behoben werden.', 1, 1050, 'active'),

('c0000000-0000-0000-0000-cd0040000001', 'R11', 'Test security of systems and networks regularly', 'Sicherheit von Systemen und Netzwerken regelmäßig testen', 'External and internal vulnerabilities shall be regularly identified, prioritized and addressed.', 'Externe und interne Schwachstellen müssen regelmäßig identifiziert, priorisiert und behoben werden.', 0, 1100, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '11.3', 'External and internal vulnerabilities regularly identified, prioritized and addressed', 'Externe und interne Schwachstellen identifiziert, priorisiert und behoben', 'External and internal vulnerabilities shall be regularly identified, prioritized and addressed.', 'Externe und interne Schwachstellen müssen regelmäßig identifiziert, priorisiert und behoben werden.', 1, 1110, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '11.4', 'External and internal penetration testing regularly performed', 'Externe und interne Penetrationstests regelmäßig durchgeführt', 'External and internal penetration testing shall be regularly performed.', 'Externe und interne Penetrationstests müssen regelmäßig durchgeführt werden.', 1, 1120, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '11.5', 'Network intrusions and unexpected file changes detected and responded to', 'Netzwerk-Intrusionen und unerwartete Dateiänderungen erkannt und behoben', 'Network intrusions and unexpected file changes shall be detected and responded to.', 'Netzwerk-Intrusionen und unerwartete Dateiänderungen müssen erkannt und behoben werden.', 1, 1130, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '11.6', 'Unauthorized changes on payment pages detected and responded to', 'Unbefugte Änderungen auf Zahlungsseiten erkannt und behoben', 'Unauthorized changes on payment pages shall be detected and responded to.', 'Unbefugte Änderungen auf Zahlungsseiten müssen erkannt und behoben werden.', 1, 1140, 'active'),

-- ── Maintain an Information Security Policy ────────────────────────────────
('c0000000-0000-0000-0000-cd0040000001', 'R12', 'Support information security with organizational policies and programs', 'Informationssicherheit durch organisatorische Richtlinien und Programme unterstützen', 'A comprehensive IS-policy shall be established, published, maintained and disseminated.', 'Eine umfassende IS-Richtlinie muss erstellt, veröffentlicht, gepflegt und verbreitet werden.', 0, 1200, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '12.1', 'Comprehensive IS policy known and current', 'Umfassende IS-Richtlinie bekannt und aktuell', 'A comprehensive IS policy shall be established, published, maintained and disseminated.', 'Eine umfassende IS-Richtlinie muss erstellt, veröffentlicht, gepflegt und verbreitet werden.', 1, 1210, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '12.3', 'Risks to the cardholder data environment are formally identified, evaluated and managed', 'Risiken für die CDE werden formell identifiziert, bewertet und gemanagt', 'Risks to the CDE shall be formally identified, evaluated and managed.', 'Risiken für die CDE müssen formell identifiziert, bewertet und gemanagt werden.', 1, 1220, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '12.5', 'PCI DSS scope documented and validated', 'PCI-DSS-Scope dokumentiert und validiert', 'PCI DSS scope shall be documented and validated.', 'Der PCI-DSS-Scope muss dokumentiert und validiert werden.', 1, 1230, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '12.6', 'Security awareness education is an ongoing activity', 'Security-Awareness-Schulung als laufende Aktivität', 'Security awareness education shall be an ongoing activity.', 'Security-Awareness-Schulung muss eine laufende Aktivität sein.', 1, 1240, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '12.7', 'Personnel are screened to reduce risks from insider threats', 'Personal überprüft zur Reduktion von Insider-Risiken', 'Personnel shall be screened to reduce risks from insider threats.', 'Personal muss überprüft werden, um Risiken durch Insider zu reduzieren.', 1, 1250, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '12.8', 'Risk to information assets associated with TPSP relationships is managed', 'Risiken durch TPSP-Beziehungen werden gemanagt', 'Risk to information assets associated with third-party service provider (TPSP) relationships shall be managed.', 'Risiken für Informationswerte aus TPSP-Beziehungen müssen gemanagt werden.', 1, 1260, 'active'),
('c0000000-0000-0000-0000-cd0040000001', '12.10', 'Suspected and confirmed security incidents that could impact the CDE are responded to immediately', 'Verdachts- und bestätigte Vorfälle mit CDE-Auswirkung werden sofort behandelt', 'Suspected and confirmed security incidents that could impact the CDE shall be responded to immediately.', 'Verdachts- und bestätigte Sicherheitsvorfälle mit möglicher CDE-Auswirkung müssen sofort behandelt werden.', 1, 1270, 'active')
ON CONFLICT (catalog_id, code) DO NOTHING;

-- Done. 12 R-headers + ~38 sub-requirements = ~50 PCI DSS v4 entries
