// AUTO-GENERATED by scripts/generate-schema-stubs.mjs on 2026-04-18T00:33:57.505Z
// 
// ADR-014 Phase 3 scaffolding. For each table that exists in
// packages/db/drizzle/*.sql but had no pgTable() export, a draft stub
// is produced below. Developer action required before wiring into
// packages/db/src/index.ts:
//   1. Move each wanted table into the appropriate domain-specific
//      file (e.g. ai-act.ts, approval.ts, audit-mgmt.ts).
//   2. Replace FK-reference comments with real .references(() => ...)
//      calls -- import the referenced tables.
//   3. Verify column-type mappings: inet became varchar(45), custom
//      enum types became varchar(500), etc.
//   4. Delete this file once all stubs are migrated.
//
// This file is NOT exported via packages/db/src/index.ts -- no build
// impact until someone explicitly wires a table.

import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  integer,
  numeric,
  timestamp,
  date,
  jsonb,
} from "drizzle-orm/pg-core";

export const aiAuthorityCommunication = pgTable(
  "ai_authority_communication",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    aiSystemId: uuid("ai_system_id") /* REFERENCES ai_system(id) — wire up manually */,
    authorityName: varchar("authority_name", { length: 500 }).notNull(),
    authorityCountry: varchar("authority_country", { length: 10 }),
    communicationType: varchar("communication_type", { length: 50 }).default('notification').notNull(),
    direction: varchar("direction", { length: 20 }).default('outgoing').notNull(),
    subject: varchar("subject", { length: 500 }).notNull(),
    content: text("content"),
    referenceNumber: varchar("reference_number", { length: 200 }),
    relatedIncidentId: uuid("related_incident_id") /* REFERENCES ai_incident(id) — wire up manually */,
    relatedActionId: uuid("related_action_id") /* REFERENCES ai_corrective_action(id) — wire up manually */,
    sentAt: timestamp("sent_at", { withTimezone: true }),
    receivedAt: timestamp("received_at", { withTimezone: true }),
    responseDeadline: timestamp("response_deadline", { withTimezone: true }),
    respondedAt: timestamp("responded_at", { withTimezone: true }),
    status: varchar("status", { length: 50 }).default('draft').notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by") /* REFERENCES user(id) — wire up manually */,
  },
);

export const aiCorrectiveAction = pgTable(
  "ai_corrective_action",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    aiSystemId: uuid("ai_system_id") /* REFERENCES ai_system(id) — wire up manually */,
    sourceType: varchar("source_type", { length: 50 }).default('non_conformity').notNull(),
    sourceId: uuid("source_id"),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    nonConformityDescription: text("non_conformity_description"),
    actionType: varchar("action_type", { length: 50 }).default('corrective').notNull(),
    isRecall: boolean("is_recall").default(false).notNull(),
    isWithdrawal: boolean("is_withdrawal").default(false).notNull(),
    recallReason: text("recall_reason"),
    priority: varchar("priority", { length: 50 }).default('medium').notNull(),
    assignedTo: uuid("assigned_to") /* REFERENCES user(id) — wire up manually */,
    dueDate: date("due_date"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    authorityNotified: boolean("authority_notified").default(false).notNull(),
    authorityNotifiedAt: timestamp("authority_notified_at", { withTimezone: true }),
    authorityReference: varchar("authority_reference", { length: 200 }),
    verificationRequired: boolean("verification_required").default(true).notNull(),
    verifiedBy: uuid("verified_by") /* REFERENCES user(id) — wire up manually */,
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    verificationNotes: text("verification_notes"),
    status: varchar("status", { length: 50 }).default('open').notNull(),
    effectivenessRating: varchar("effectiveness_rating", { length: 50 }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const aiGpaiModel = pgTable(
  "ai_gpai_model",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    name: varchar("name", { length: 500 }).notNull(),
    provider: varchar("provider", { length: 500 }).notNull(),
    modelType: varchar("model_type", { length: 50 }).default('general_purpose').notNull(),
    systemicRiskJustification: text("systemic_risk_justification"),
    trainingDataSummary: text("training_data_summary"),
    computationalResources: text("computational_resources"),
    energyConsumptionKwh: numeric("energy_consumption_kwh"),
    adversarialTestingResults: jsonb("adversarial_testing_results").default('{}'),
    incidentReportingEnabled: boolean("incident_reporting_enabled").default(false).notNull(),
    cybersecurityMeasures: text("cybersecurity_measures"),
    euRepresentativeContact: varchar("eu_representative_contact", { length: 500 }),
    codeOfPracticeNotes: text("code_of_practice_notes"),
    releaseDate: date("release_date"),
    status: varchar("status", { length: 50 }).default('registered').notNull(),
    capabilitiesSummary: text("capabilities_summary"),
    limitationsSummary: text("limitations_summary"),
    intendedUse: text("intended_use"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by") /* REFERENCES user(id) — wire up manually */,
    updatedBy: uuid("updated_by") /* REFERENCES user(id) — wire up manually */,
  },
);

export const aiIncident = pgTable(
  "ai_incident",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    aiSystemId: uuid("ai_system_id") /* REFERENCES ai_system(id) — wire up manually */,
    gpaiModelId: uuid("gpai_model_id") /* REFERENCES ai_gpai_model(id) — wire up manually */,
    incidentCode: varchar("incident_code", { length: 50 }),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    severity: varchar("severity", { length: 50 }).default('medium').notNull(),
    isSerious: boolean("is_serious").default(false).notNull(),
    seriousCriteria: jsonb("serious_criteria").default('[]'),
    detectedAt: timestamp("detected_at", { withTimezone: true }).defaultNow().notNull(),
    authorityDeadline: timestamp("authority_deadline", { withTimezone: true }),
    authorityNotifiedAt: timestamp("authority_notified_at", { withTimezone: true }),
    authorityReference: varchar("authority_reference", { length: 200 }),
    affectedPersonsCount: integer("affected_persons_count"),
    harmType: varchar("harm_type", { length: 100 }),
    harmDescription: text("harm_description"),
    rootCause: text("root_cause"),
    rootCauseCategory: varchar("root_cause_category", { length: 100 }),
    remediationActions: text("remediation_actions"),
    preventiveMeasures: text("preventive_measures"),
    status: varchar("status", { length: 50 }).default('detected').notNull(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    lessonsLearned: text("lessons_learned"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by") /* REFERENCES user(id) — wire up manually */,
  },
);

export const aiPenalty = pgTable(
  "ai_penalty",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    aiSystemId: uuid("ai_system_id") /* REFERENCES ai_system(id) — wire up manually */,
    authorityName: varchar("authority_name", { length: 500 }).notNull(),
    penaltyType: varchar("penalty_type", { length: 50 }).default('fine').notNull(),
    articleReference: varchar("article_reference", { length: 100 }),
    fineAmount: numeric("fine_amount"),
    fineCurrency: varchar("fine_currency", { length: 10 }).default('EUR'),
    finePercentageTurnover: numeric("fine_percentage_turnover"),
    penaltyBracket: varchar("penalty_bracket", { length: 50 }),
    status: varchar("status", { length: 50 }).default('imposed').notNull(),
    appealFiled: boolean("appeal_filed").default(false),
    appealStatus: varchar("appeal_status", { length: 50 }),
    appealDeadline: date("appeal_deadline"),
    paidAt: timestamp("paid_at", { withTimezone: true }),
    description: text("description"),
    violationDescription: text("violation_description"),
    imposedAt: date("imposed_at")/* DEFAULT CURRENT_DATE */.notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const aiProhibitedScreening = pgTable(
  "ai_prohibited_screening",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    aiSystemId: uuid("ai_system_id").notNull() /* REFERENCES ai_system(id) — wire up manually */,
    screeningDate: timestamp("screening_date", { withTimezone: true }).defaultNow().notNull(),
    screenedBy: uuid("screened_by") /* REFERENCES user(id) — wire up manually */,
    subliminalManipulation: boolean("subliminal_manipulation").default(false).notNull(),
    exploitationVulnerable: boolean("exploitation_vulnerable").default(false).notNull(),
    socialScoring: boolean("social_scoring").default(false).notNull(),
    predictivePolicingIndividual: boolean("predictive_policing_individual").default(false).notNull(),
    facialRecognitionScraping: boolean("facial_recognition_scraping").default(false).notNull(),
    emotionInferenceWorkplace: boolean("emotion_inference_workplace").default(false).notNull(),
    biometricCategorization: boolean("biometric_categorization").default(false).notNull(),
    realTimeBiometricPublic: boolean("real_time_biometric_public").default(false).notNull(),
    hasProhibitedPractice: varchar("has_prohibited_practice", { length: 500 }) /* TYPE: BOOLEAN GENERATED ALWAYS AS (
    subliminal_manipulation OR exploitation_vulnerable OR social_scoring OR
    predictive_policing_individual OR facial_recognition_scraping OR
    emotion_inference_workplace OR biometric_categorization OR real_time_biometric_public
  ) STORED */,
    justification: text("justification"),
    exceptionApplied: boolean("exception_applied").default(false),
    exceptionJustification: text("exception_justification"),
    status: varchar("status", { length: 50 }).default('completed').notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const aiProviderQms = pgTable(
  "ai_provider_qms",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    aiSystemId: uuid("ai_system_id") /* REFERENCES ai_system(id) — wire up manually */,
    riskManagementProcedure: boolean("risk_management_procedure").default(false).notNull(),
    dataGovernanceProcedure: boolean("data_governance_procedure").default(false).notNull(),
    technicalDocumentationProcedure: boolean("technical_documentation_procedure").default(false).notNull(),
    recordKeepingProcedure: boolean("record_keeping_procedure").default(false).notNull(),
    transparencyProcedure: boolean("transparency_procedure").default(false).notNull(),
    humanOversightProcedure: boolean("human_oversight_procedure").default(false).notNull(),
    accuracyRobustnessProcedure: boolean("accuracy_robustness_procedure").default(false).notNull(),
    cybersecurityProcedure: boolean("cybersecurity_procedure").default(false).notNull(),
    incidentReportingProcedure: boolean("incident_reporting_procedure").default(false).notNull(),
    thirdPartyManagementProcedure: boolean("third_party_management_procedure").default(false).notNull(),
    overallMaturity: integer("overall_maturity").default(0),
    lastAuditDate: date("last_audit_date"),
    nextAuditDate: date("next_audit_date"),
    status: varchar("status", { length: 50 }).default('draft').notNull(),
    responsibleId: uuid("responsible_id") /* REFERENCES user(id) — wire up manually */,
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const approvalDecision = pgTable(
  "approval_decision",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    requestId: uuid("request_id").notNull() /* REFERENCES approval_request(id) — wire up manually */,
    stepNumber: integer("step_number").notNull(),
    approverId: uuid("approver_id").notNull(),
    decision: varchar("decision", { length: 20 }).notNull(),
    comment: text("comment"),
    decidedAt: timestamp("decided_at", { withTimezone: true }).defaultNow().notNull(),
    delegatedFrom: uuid("delegated_from"),
  },
);

export const approvalRequest = pgTable(
  "approval_request",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    workflowId: uuid("workflow_id") /* REFERENCES approval_workflow(id) — wire up manually */,
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    entityId: uuid("entity_id").notNull(),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    currentStep: integer("current_step").default(0).notNull(),
    status: varchar("status", { length: 20 }).default('pending').notNull(),
    requestedBy: uuid("requested_by").notNull(),
    requestedAt: timestamp("requested_at", { withTimezone: true }).defaultNow().notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    dueDate: date("due_date"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const approvalWorkflow = pgTable(
  "approval_workflow",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    workflowType: varchar("workflow_type", { length: 50 }).default('sequential').notNull(),
    entityType: varchar("entity_type", { length: 50 }),
    steps: jsonb("steps").default('[]').notNull(),
    isTemplate: boolean("is_template").default(false).notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const attestationCampaign = pgTable(
  "attestation_campaign",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    campaignType: varchar("campaign_type", { length: 30 }).default('policy').notNull(),
    targetRole: varchar("target_role", { length: 50 }),
    dueDate: date("due_date").notNull(),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const attestationResponse = pgTable(
  "attestation_response",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    campaignId: uuid("campaign_id").notNull() /* REFERENCES attestation_campaign(id) — wire up manually */,
    userId: uuid("user_id").notNull(),
    policyId: uuid("policy_id"),
    response: varchar("response", { length: 20 }).default('pending').notNull(),
    comment: text("comment"),
    attestedAt: timestamp("attested_at", { withTimezone: true }),
    reminderSentAt: timestamp("reminder_sent_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const auditSample = pgTable(
  "audit_sample",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    controlId: uuid("control_id"),
    auditId: uuid("audit_id"),
    campaignId: uuid("campaign_id"),
    sampleMethod: varchar("sample_method", { length: 30 }).default('random').notNull(),
    populationSize: integer("population_size").notNull(),
    sampleSize: integer("sample_size").notNull(),
    sampleItems: jsonb("sample_items").default('[]').notNull(),
    results: jsonb("results").default('{}'),
    exceptionsFound: integer("exceptions_found").default(0),
    status: varchar("status", { length: 20 }).default('planned').notNull(),
    sampledAt: timestamp("sampled_at", { withTimezone: true }),
    sampledBy: uuid("sampled_by"),
    reviewedBy: uuid("reviewed_by"),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const boardReport = pgTable(
  "board_report",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    title: varchar("title", { length: 500 }).notNull(),
    reportType: varchar("report_type", { length: 30 }).default('quarterly').notNull(),
    reportingPeriod: varchar("reporting_period", { length: 10 }),
    sections: jsonb("sections").default('[]').notNull(),
    dataSnapshots: jsonb("data_snapshots").default('{}'),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    presentedAt: date("presented_at"),
    presentedTo: varchar("presented_to", { length: 255 }),
    approvedBy: uuid("approved_by"),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const catalogEntryMapping = pgTable(
  "catalog_entry_mapping",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sourceEntryId: uuid("source_entry_id").notNull() /* REFERENCES catalog_entry(id) — wire up manually */,
    targetEntryId: uuid("target_entry_id").notNull() /* REFERENCES catalog_entry(id) — wire up manually */,
    relationship: varchar("relationship", { length: 500 }) /* TYPE: mapping_relationship */.default('equivalent').notNull(),
    confidence: integer("confidence").default(85).notNull(),
    mappingSource: varchar("mapping_source", { length: 500 }) /* TYPE: mapping_source */.default('official').notNull(),
    sourceReference: text("source_reference"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const checklistInstance = pgTable(
  "checklist_instance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    templateId: uuid("template_id") /* REFERENCES checklist_template(id) — wire up manually */,
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }),
    entityId: uuid("entity_id"),
    name: varchar("name", { length: 255 }).notNull(),
    items: jsonb("items").default('[]').notNull(),
    completedItems: integer("completed_items").default(0),
    totalItems: integer("total_items").default(0),
    status: varchar("status", { length: 20 }).default('open').notNull(),
    assignedTo: uuid("assigned_to"),
    dueDate: date("due_date"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const checklistTemplate = pgTable(
  "checklist_template",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    category: varchar("category", { length: 50 }),
    items: jsonb("items").default('[]').notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const connectorFieldMapping = pgTable(
  "connector_field_mapping",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    connectorId: uuid("connector_id").notNull() /* REFERENCES connector_instance(id) — wire up manually */,
    sourceField: varchar("source_field", { length: 255 }).notNull(),
    targetEntity: varchar("target_entity", { length: 50 }).notNull(),
    targetField: varchar("target_field", { length: 100 }).notNull(),
    transformation: varchar("transformation", { length: 50 }).default('direct'),
    transformConfig: jsonb("transform_config").default('{}'),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const connectorInstance = pgTable(
  "connector_instance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    connectorType: varchar("connector_type", { length: 50 }).notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    authMethod: varchar("auth_method", { length: 30 }).default('oauth2').notNull(),
    config: jsonb("config").default('{}').notNull(),
    credentialsEncrypted: text("credentials_encrypted"),
    syncDirection: varchar("sync_direction", { length: 20 }).default('pull').notNull(),
    syncFrequency: varchar("sync_frequency", { length: 20 }).default('daily'),
    lastSyncAt: timestamp("last_sync_at", { withTimezone: true }),
    lastSyncStatus: varchar("last_sync_status", { length: 20 }),
    lastSyncRecords: integer("last_sync_records"),
    lastError: text("last_error"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const connectorSyncLog = pgTable(
  "connector_sync_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    connectorId: uuid("connector_id").notNull() /* REFERENCES connector_instance(id) — wire up manually */,
    orgId: uuid("org_id").notNull(),
    syncType: varchar("sync_type", { length: 20 }).default('full').notNull(),
    status: varchar("status", { length: 20 }).notNull(),
    recordsPulled: integer("records_pulled").default(0),
    recordsPushed: integer("records_pushed").default(0),
    recordsFailed: integer("records_failed").default(0),
    errorDetails: jsonb("error_details").default('[]'),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    durationMs: integer("duration_ms"),
  },
);

export const connectorTypeDefinition = pgTable(
  "connector_type_definition",
  {
    connectorType: varchar("connector_type", { length: 50 }).primaryKey(),
    displayName: varchar("display_name", { length: 255 }).notNull(),
    displayNameDe: varchar("display_name_de", { length: 255 }),
    category: varchar("category", { length: 50 }).notNull(),
    description: text("description"),
    descriptionDe: text("description_de"),
    icon: varchar("icon", { length: 50 }),
    configSchema: jsonb("config_schema").default('{}'),
    isAvailable: boolean("is_available").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const consolidationEntry = pgTable(
  "consolidation_entry",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    groupId: uuid("group_id").notNull() /* REFERENCES consolidation_group(id) — wire up manually */,
    orgId: uuid("org_id").notNull(),
    entityId: uuid("entity_id").notNull(),
    reportingPeriod: varchar("reporting_period", { length: 10 }).notNull(),
    entryType: varchar("entry_type", { length: 30 }).default('reported').notNull(),
    accountCode: varchar("account_code", { length: 50 }),
    accountName: varchar("account_name", { length: 255 }),
    currency: varchar("currency", { length: 3 }).default('EUR'),
    eliminationType: varchar("elimination_type", { length: 30 }),
    notes: text("notes"),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const consolidationGroup = pgTable(
  "consolidation_group",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    parentEntityId: uuid("parent_entity_id"),
    consolidationMethod: varchar("consolidation_method", { length: 30 }).default('full').notNull(),
    currency: varchar("currency", { length: 3 }).default('EUR'),
    fiscalYearEnd: varchar("fiscal_year_end", { length: 5 }).default('12-31'),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const contentPlaceholder = pgTable(
  "content_placeholder",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    token: varchar("token", { length: 100 }).notNull(),
    label: varchar("label", { length: 255 }).notNull(),
    description: text("description"),
    sourceType: varchar("source_type", { length: 50 }),
    sourceId: uuid("source_id"),
    sourceField: varchar("source_field", { length: 100 }),
    staticValue: text("static_value"),
    formatPattern: varchar("format_pattern", { length: 100 }),
    category: varchar("category", { length: 50 }),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const contentRequest = pgTable(
  "content_request",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }),
    entityId: uuid("entity_id"),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    requestedFields: jsonb("requested_fields").default('[]'),
    requestedFrom: uuid("requested_from").notNull(),
    requestedBy: uuid("requested_by").notNull(),
    dueDate: date("due_date"),
    priority: varchar("priority", { length: 20 }).default('medium'),
    status: varchar("status", { length: 20 }).default('pending').notNull(),
    responseData: jsonb("response_data").default('{}'),
    respondedAt: timestamp("responded_at", { withTimezone: true }),
    reminderCount: integer("reminder_count").default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const controlMonitoringResult = pgTable(
  "control_monitoring_result",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ruleId: uuid("rule_id").notNull() /* REFERENCES control_monitoring_rule(id) — wire up manually */,
    orgId: uuid("org_id").notNull(),
    result: varchar("result", { length: 20 }).notNull(),
    details: jsonb("details").default('{}'),
    checkedAt: timestamp("checked_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const controlMonitoringRule = pgTable(
  "control_monitoring_rule",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    controlId: uuid("control_id"),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    ruleType: varchar("rule_type", { length: 30 }).default('threshold').notNull(),
    configuration: jsonb("configuration").default('{}').notNull(),
    checkFrequency: varchar("check_frequency", { length: 20 }).default('daily').notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    lastCheckedAt: timestamp("last_checked_at", { withTimezone: true }),
    lastResult: varchar("last_result", { length: 20 }),
    consecutiveFailures: integer("consecutive_failures").default(0),
    alertThreshold: integer("alert_threshold").default(3),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const dataLineageEntry = pgTable(
  "data_lineage_entry",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    entityId: uuid("entity_id").notNull(),
    fieldName: varchar("field_name", { length: 100 }).notNull(),
    fieldValue: text("field_value"),
    sourceId: uuid("source_id") /* REFERENCES data_lineage_source(id) — wire up manually */,
    sourceRecord: varchar("source_record", { length: 500 }),
    transformation: text("transformation"),
    confidence: varchar("confidence", { length: 20 }).default('verified'),
    verifiedBy: uuid("verified_by"),
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const dataLineageSource = pgTable(
  "data_lineage_source",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    sourceName: varchar("source_name", { length: 255 }).notNull(),
    sourceType: varchar("source_type", { length: 50 }).default('manual').notNull(),
    connectionId: uuid("connection_id"),
    description: text("description"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const dataLink = pgTable(
  "data_link",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    sourceType: varchar("source_type", { length: 50 }).notNull(),
    sourceId: uuid("source_id").notNull(),
    sourceField: varchar("source_field", { length: 100 }).notNull(),
    targetType: varchar("target_type", { length: 50 }).notNull(),
    targetId: uuid("target_id").notNull(),
    targetField: varchar("target_field", { length: 100 }).notNull(),
    linkType: varchar("link_type", { length: 30 }).default('reference').notNull(),
    isBidirectional: boolean("is_bidirectional").default(false),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const dataValidationResult = pgTable(
  "data_validation_result",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ruleId: uuid("rule_id").notNull() /* REFERENCES data_validation_rule(id) — wire up manually */,
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    entityId: uuid("entity_id").notNull(),
    fieldName: varchar("field_name", { length: 100 }).notNull(),
    fieldValue: text("field_value"),
    isValid: boolean("is_valid").notNull(),
    message: text("message"),
    checkedAt: timestamp("checked_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const dataValidationRule = pgTable(
  "data_validation_rule",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    fieldName: varchar("field_name", { length: 100 }).notNull(),
    ruleType: varchar("rule_type", { length: 30 }).default('range').notNull(),
    configuration: jsonb("configuration").default('{}').notNull(),
    severity: varchar("severity", { length: 20 }).default('warning').notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const ermSyncConfig = pgTable(
  "erm_sync_config",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    moduleKey: varchar("module_key", { length: 50 }).notNull(),
    syncEnabled: boolean("sync_enabled").default(true).notNull(),
    scoreThreshold: integer("score_threshold").default(15).notNull(),
    autoCreateRisk: boolean("auto_create_risk").default(true).notNull(),
    defaultRiskCategory: varchar("default_risk_category", { length: 50 }).default('operational').notNull(),
    defaultTreatmentStrategy: varchar("default_treatment_strategy", { length: 20 }).default('mitigate').notNull(),
    notifyRiskManager: boolean("notify_risk_manager").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const esefFiling = pgTable(
  "esef_filing",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    fiscalYear: integer("fiscal_year").notNull(),
    leiCode: varchar("lei_code", { length: 20 }),
    filingType: varchar("filing_type", { length: 30 }).default('annual').notNull(),
    taxonomyVersion: varchar("taxonomy_version", { length: 50 }),
    documentId: uuid("document_id"),
    xhtmlContent: text("xhtml_content"),
    validationStatus: varchar("validation_status", { length: 20 }).default('not_validated'),
    validationErrors: jsonb("validation_errors").default('[]'),
    filedAt: timestamp("filed_at", { withTimezone: true }),
    filedTo: varchar("filed_to", { length: 100 }),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const euTaxonomyAssessment = pgTable(
  "eu_taxonomy_assessment",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    reportingYear: integer("reporting_year").notNull(),
    activityName: varchar("activity_name", { length: 500 }).notNull(),
    naceCode: varchar("nace_code", { length: 20 }),
    objectiveId: varchar("objective_id", { length: 10 }).notNull(),
    isEligible: boolean("is_eligible"),
    isAligned: boolean("is_aligned"),
    substantialContributionMet: boolean("substantial_contribution_met").default(false),
    dnshMet: boolean("dnsh_met").default(false),
    minimumSafeguardsMet: boolean("minimum_safeguards_met").default(false),
    justification: text("justification"),
    assessedBy: uuid("assessed_by"),
    assessedAt: timestamp("assessed_at", { withTimezone: true }),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const evidenceRequest = pgTable(
  "evidence_request",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    controlId: uuid("control_id"),
    auditId: uuid("audit_id"),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    requestedFrom: uuid("requested_from").notNull(),
    requestedBy: uuid("requested_by").notNull(),
    dueDate: date("due_date"),
    priority: varchar("priority", { length: 20 }).default('medium'),
    status: varchar("status", { length: 20 }).default('pending').notNull(),
    evidenceId: uuid("evidence_id"),
    responseNote: text("response_note"),
    respondedAt: timestamp("responded_at", { withTimezone: true }),
    reminderCount: integer("reminder_count").default(0),
    lastReminder: timestamp("last_reminder", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const exceptionReport = pgTable(
  "exception_report",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    entityId: uuid("entity_id").notNull(),
    exceptionType: varchar("exception_type", { length: 50 }).notNull(),
    severity: varchar("severity", { length: 20 }).default('medium').notNull(),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    detectedMethod: varchar("detected_method", { length: 30 }).default('manual').notNull(),
    expectedValue: text("expected_value"),
    actualValue: text("actual_value"),
    isResolved: boolean("is_resolved").default(false).notNull(),
    resolvedBy: uuid("resolved_by"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    resolutionNote: text("resolution_note"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const inlineComment = pgTable(
  "inline_comment",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    entityId: uuid("entity_id").notNull(),
    fieldName: varchar("field_name", { length: 100 }),
    content: text("content").notNull(),
    parentId: uuid("parent_id") /* REFERENCES inline_comment(id) — wire up manually */,
    isResolved: boolean("is_resolved").default(false).notNull(),
    resolvedBy: uuid("resolved_by"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by").notNull(),
  },
);

export const ismsCorrectiveAction = pgTable(
  "isms_corrective_action",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    nonconformityId: uuid("nonconformity_id").notNull() /* REFERENCES isms_nonconformity(id) — wire up manually */,
    description: text("description"),
    actionType: varchar("action_type", { length: 50 }).default('corrective').notNull(),
    dueDate: date("due_date"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    verifiedBy: uuid("verified_by") /* REFERENCES user(id) — wire up manually */,
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    verificationResult: varchar("verification_result", { length: 50 }),
    verificationNotes: text("verification_notes"),
    effectivenessRating: varchar("effectiveness_rating", { length: 50 }),
    effectivenessNotes: text("effectiveness_notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const ismsNonconformity = pgTable(
  "isms_nonconformity",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    complaint: varchar("complaint", { length: 500 }) /* TYPE: source_type VARCHAR(50) */.default('internal_audit').notNull(),
    sourceId: uuid("source_id"),
    sourceReference: varchar("source_reference", { length: 200 }),
    category: varchar("category", { length: 100 }),
    isoClause: varchar("iso_clause", { length: 50 }),
    dueDate: date("due_date"),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    assignedTo: uuid("assigned_to") /* REFERENCES user(id) — wire up manually */,
    rootCauseMethod: varchar("root_cause_method", { length: 50 }),
    reopened: varchar("reopened", { length: 500 }) /* TYPE: status VARCHAR(30) */.default('open').notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const messagingIntegration = pgTable(
  "messaging_integration",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    provider: varchar("provider", { length: 30 }).notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    webhookUrl: text("webhook_url"),
    channelId: varchar("channel_id", { length: 255 }),
    isActive: boolean("is_active").default(true).notNull(),
    lastSentAt: timestamp("last_sent_at", { withTimezone: true }),
    errorCount: integer("error_count").default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const moduleNavItem = pgTable(
  "module_nav_item",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    moduleKey: varchar("module_key", { length: 50 }).notNull() /* REFERENCES module_definition(module_key) — wire up manually */,
    labelDe: varchar("label_de", { length: 200 }).notNull(),
    labelEn: varchar("label_en", { length: 200 }).notNull(),
    icon: varchar("icon", { length: 50 }),
    route: varchar("route", { length: 200 }).notNull(),
    sortOrder: integer("sort_order").default(0).notNull(),
    parentRoute: varchar("parent_route", { length: 200 }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const narrativeInstance = pgTable(
  "narrative_instance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    templateId: uuid("template_id") /* REFERENCES narrative_template(id) — wire up manually */,
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }),
    entityId: uuid("entity_id"),
    reportId: uuid("report_id"),
    renderedContent: text("rendered_content"),
    dataSnapshot: jsonb("data_snapshot").default('{}'),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const narrativeTemplate = pgTable(
  "narrative_template",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    category: varchar("category", { length: 50 }),
    contentBlocks: jsonb("content_blocks").default('[]').notNull(),
    language: varchar("language", { length: 5 }).default('de'),
    version: integer("version").default(1).notNull(),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const reminderRule = pgTable(
  "reminder_rule",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    conditionField: varchar("condition_field", { length: 100 }).notNull(),
    conditionType: varchar("condition_type", { length: 30 }).default('days_before_due').notNull(),
    conditionValue: integer("condition_value").default(7).notNull(),
    channel: varchar("channel", { length: 20 }).default('in_app').notNull(),
    template: text("template"),
    isActive: boolean("is_active").default(true).notNull(),
    lastExecuted: timestamp("last_executed", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const reviewCycle = pgTable(
  "review_cycle",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    entityType: varchar("entity_type", { length: 50 }).notNull(),
    entityId: uuid("entity_id").notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    reviewers: jsonb("reviewers").default('[]').notNull(),
    currentReviewerIndex: integer("current_reviewer_index").default(0),
    status: varchar("status", { length: 20 }).default('pending').notNull(),
    escalationDays: integer("escalation_days").default(5),
    escalationTo: uuid("escalation_to"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    dueDate: date("due_date"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by").notNull(),
  },
);

export const reviewDecision = pgTable(
  "review_decision",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    cycleId: uuid("cycle_id").notNull() /* REFERENCES review_cycle(id) — wire up manually */,
    reviewerId: uuid("reviewer_id").notNull(),
    decision: varchar("decision", { length: 20 }).notNull(),
    comment: text("comment"),
    decidedAt: timestamp("decided_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const riskAcceptance = pgTable(
  "risk_acceptance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    riskId: uuid("risk_id").notNull() /* REFERENCES risk(id) — wire up manually */,
    acceptedAt: timestamp("accepted_at", { withTimezone: true }).defaultNow().notNull(),
    riskLevelAtAcceptance: varchar("risk_level_at_acceptance", { length: 20 }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: uuid("revoked_by") /* REFERENCES user(id) — wire up manually */,
    revokeReason: text("revoke_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const riskAcceptanceAuthority = pgTable(
  "risk_acceptance_authority",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull() /* REFERENCES organization(id) — wire up manually */,
    maxScore: integer("max_score").default(25).notNull(),
    requiredRole: varchar("required_role", { length: 50 }).notNull(),
    requiredRoleLabel: varchar("required_role_label", { length: 200 }),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const rootCauseAnalysis = pgTable(
  "root_cause_analysis",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    findingId: uuid("finding_id"),
    incidentId: uuid("incident_id"),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    methodology: varchar("methodology", { length: 50 }).default('5_why').notNull(),
    rootCauses: jsonb("root_causes").default('[]').notNull(),
    contributingFactors: jsonb("contributing_factors").default('[]'),
    correctiveActions: jsonb("corrective_actions").default('[]'),
    preventiveActions: jsonb("preventive_actions").default('[]'),
    status: varchar("status", { length: 20 }).default('open').notNull(),
    ownerId: uuid("owner_id"),
    dueDate: date("due_date"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const soxScoping = pgTable(
  "sox_scoping",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    fiscalYear: integer("fiscal_year").notNull(),
    currency: varchar("currency", { length: 3 }).default('EUR'),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
    scopedLocations: jsonb("scoped_locations").default('[]'),
    scopedAccounts: jsonb("scoped_accounts").default('[]'),
    scopedAssertions: jsonb("scoped_assertions").default('[]'),
    totalControls: integer("total_controls").default(0),
    inScopeControls: integer("in_scope_controls").default(0),
    approvedBy: uuid("approved_by"),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const tagDefinition = pgTable(
  "tag_definition",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    name: varchar("name", { length: 100 }).notNull(),
    color: varchar("color", { length: 7 }).default('#6B7280'),
    category: varchar("category", { length: 50 }),
    description: text("description"),
    usageCount: integer("usage_count").default(0).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    createdBy: uuid("created_by"),
  },
);

export const xbrlTag = pgTable(
  "xbrl_tag",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    taxonomyId: uuid("taxonomy_id").notNull() /* REFERENCES xbrl_taxonomy(id) — wire up manually */,
    elementName: varchar("element_name", { length: 500 }).notNull(),
    labelEn: varchar("label_en", { length: 500 }),
    labelDe: varchar("label_de", { length: 500 }),
    dataType: varchar("data_type", { length: 50 }),
    periodType: varchar("period_type", { length: 20 }),
    balanceType: varchar("balance_type", { length: 20 }),
    isAbstract: boolean("is_abstract").default(false),
    parentId: uuid("parent_id") /* REFERENCES xbrl_tag(id) — wire up manually */,
    sortOrder: integer("sort_order").default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const xbrlTaggingInstance = pgTable(
  "xbrl_tagging_instance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull(),
    reportId: uuid("report_id"),
    documentId: uuid("document_id"),
    taxonomyId: uuid("taxonomy_id").notNull() /* REFERENCES xbrl_taxonomy(id) — wire up manually */,
    tagId: uuid("tag_id").notNull() /* REFERENCES xbrl_tag(id) — wire up manually */,
    taggedValue: text("tagged_value"),
    contextPeriod: varchar("context_period", { length: 50 }),
    contextEntity: varchar("context_entity", { length: 255 }),
    unit: varchar("unit", { length: 50 }),
    decimals: integer("decimals"),
    isExtension: boolean("is_extension").default(false),
    taggedBy: uuid("tagged_by"),
    taggedAt: timestamp("tagged_at", { withTimezone: true }).defaultNow().notNull(),
    status: varchar("status", { length: 20 }).default('draft').notNull(),
  },
);

export const xbrlTaxonomy = pgTable(
  "xbrl_taxonomy",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: varchar("name", { length: 255 }).notNull(),
    version: varchar("version", { length: 50 }).notNull(),
    taxonomyType: varchar("taxonomy_type", { length: 30 }).notNull(),
    namespaceUri: text("namespace_uri"),
    entryPointUrl: text("entry_point_url"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);
