// Sprint 1.4: Work Item Schema (Drizzle ORM)
// Base entity pattern for all GRC objects (PRD §032)
// Entities: work_item_type (platform-wide), work_item, work_item_link

import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  timestamp,
  pgEnum,
  integer,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { organization, user } from "./platform";

// ──────────────────────────────────────────────────────────────
// Enums
// ──────────────────────────────────────────────────────────────

export const workItemStatusGenericEnum = pgEnum("work_item_status_generic", [
  "draft",
  "in_evaluation",
  "in_review",
  "in_approval",
  "management_approved",
  "active",
  "in_treatment",
  "completed",
  "obsolete",
  "cancelled",
]);

// ──────────────────────────────────────────────────────────────
// 4.1 WorkItemType — Platform-wide type registry
//     No org_id, no RLS. One row per GRC object type.
// ──────────────────────────────────────────────────────────────

export const workItemType = pgTable("work_item_type", {
  typeKey: varchar("type_key", { length: 50 }).primaryKey(),
  displayNameDe: varchar("display_name_de", { length: 100 }).notNull(),
  displayNameEn: varchar("display_name_en", { length: 100 }).notNull(),
  icon: varchar("icon", { length: 50 }),
  colorClass: varchar("color_class", { length: 50 }),
  primaryModule: varchar("primary_module", { length: 50 }).notNull(),
  secondaryModules: text("secondary_modules")
    .array()
    .notNull()
    .default(sql`'{}'::text[]`),
  hasStatusWorkflow: boolean("has_status_workflow").notNull().default(true),
  hasResponsibleUser: boolean("has_responsible_user").notNull().default(true),
  hasDueDate: boolean("has_due_date").notNull().default(false),
  hasPriority: boolean("has_priority").notNull().default(false),
  hasLinkedAsset: boolean("has_linked_asset").notNull().default(false),
  hasCiaEvaluation: boolean("has_cia_evaluation").notNull().default(false),
  isCrossModule: boolean("is_cross_module").notNull().default(false),
  statusEnumName: varchar("status_enum_name", { length: 50 }),
  dataTable: varchar("data_table", { length: 100 }),
  dataFkColumn: varchar("data_fk_column", { length: 50 }),
  elementIdPrefix: varchar("element_id_prefix", { length: 3 }),
  navOrder: integer("nav_order").notNull(),
  isActiveInPlatform: boolean("is_active_in_platform").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ──────────────────────────────────────────────────────────────
// 4.2 WorkItem — Base entity for all GRC objects
//     Has org_id + RLS. Element ID generated by trigger.
// ──────────────────────────────────────────────────────────────

export const workItem = pgTable(
  "work_item",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organization.id),
    typeKey: varchar("type_key", { length: 50 })
      .notNull()
      .references(() => workItemType.typeKey),
    elementId: varchar("element_id", { length: 20 }), // populated by trigger
    name: varchar("name", { length: 500 }).notNull(),
    status: workItemStatusGenericEnum("status").notNull().default("draft"),
    responsibleId: uuid("responsible_id").references(() => user.id),
    reviewerId: uuid("reviewer_id").references(() => user.id),
    dueDate: timestamp("due_date", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    completedBy: uuid("completed_by").references(() => user.id),
    grcPerspective: text("grc_perspective")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    // Cross-cutting mandatory fields
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    deletedBy: uuid("deleted_by"),
  },
  (table) => [
    index("work_item_org_type_idx").on(table.orgId, table.typeKey),
    index("work_item_org_status_idx").on(table.orgId, table.status),
    index("work_item_responsible_idx").on(table.responsibleId),
  ],
);

// ──────────────────────────────────────────────────────────────
// 4.3 WorkItemLink — Cross-references between work items
//     UNIQUE(source_id, target_id, link_type) + CHECK(source != target)
//     added in migration SQL.
// ──────────────────────────────────────────────────────────────

export const workItemLink = pgTable(
  "work_item_link",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organization.id),
    sourceId: uuid("source_id")
      .notNull()
      .references(() => workItem.id, { onDelete: "cascade" }),
    targetId: uuid("target_id")
      .notNull()
      .references(() => workItem.id, { onDelete: "cascade" }),
    linkType: varchar("link_type", { length: 50 }).notNull().default("related"),
    linkContext: text("link_context"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid("created_by").references(() => user.id),
  },
  (table) => [
    index("work_item_link_source_idx").on(table.sourceId),
    index("work_item_link_target_idx").on(table.targetId),
  ],
);
