#!/usr/bin/env node
// generate-openapi.mjs
//
// Walks apps/web/src/app/api/v1/ and produces an OpenAPI 3.1 skeleton
// at docs/openapi.yaml. For each route.ts file, extracts:
//   - path (from folder structure)
//   - HTTP methods (from exported async function names)
//   - roles required (from withAuth("...") arguments)
//   - request body schema (static -- just records whether one is parsed)
//   - path parameters (from [param] folders)
//
// The output is INTENTIONALLY not a full spec with complete Zod-to-
// OpenAPI-type-mapping -- that would require changing how every route
// declares its schema. It's a skeleton good enough for:
//   - External consumers seeing the API surface
//   - Tooling like curl-scripts / Bruno collections
//   - CI-gate: detecting accidentally-exposed endpoints
//
// Full Zod→OpenAPI (response types, examples) is a follow-up once the
// schemas move to a Zod-Adapter that exports JSON Schema.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const API_DIR = join(ROOT, "apps/web/src/app/api/v1");
const OUT = join(ROOT, "docs/openapi.yaml");

async function walk(dir) {
  const out = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else if (entry.name === "route.ts" || entry.name === "route.tsx") out.push(full);
  }
  return out;
}

function pathFromFile(absPath) {
  // Normalize Windows backslashes + double-slash artifacts from the
  // URL→path conversion in ROOT.
  const norm = absPath.replace(/\\/g, "/").replace(/\/+/g, "/");
  const marker = "apps/web/src/app/api/v1/";
  const idx = norm.indexOf(marker);
  if (idx < 0) return norm;
  const rel = norm.slice(idx + marker.length);
  return (
    "/api/v1/" +
    rel.replace(/\/route\.tsx?$/, "").replace(/\[([^\]]+)\]/g, "{$1}")
  );
}

function extractMethods(src) {
  return ["get", "post", "put", "patch", "delete"].filter((m) =>
    new RegExp(`export\\s+async\\s+function\\s+${m.toUpperCase()}\\b`).test(src),
  );
}

function extractRoles(src) {
  const re = /withAuth\(([^)]*)\)/g;
  const out = new Set();
  let m;
  while ((m = re.exec(src)) !== null) {
    for (const raw of m[1].split(",")) {
      const clean = raw.trim().replace(/^["']|["']$/g, "");
      if (clean) out.add(clean);
    }
  }
  return [...out];
}

function pathParams(path) {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
}

async function main() {
  const files = await walk(API_DIR);
  files.sort();

  const paths = {};
  for (const file of files) {
    const src = await readFile(file, "utf8");
    const path = pathFromFile(file);
    const methods = extractMethods(src);
    const roles = extractRoles(src);
    const params = pathParams(path);

    if (methods.length === 0) continue;
    paths[path] = paths[path] ?? {};
    for (const method of methods) {
      paths[path][method] = {
        summary: `${method.toUpperCase()} ${path}`,
        tags: [tagFor(path)],
        security: roles.length > 0 ? [{ bearerAuth: roles }] : [],
        parameters: params.map((p) => ({
          name: p,
          in: "path",
          required: true,
          schema: { type: "string", format: p === "id" || p.endsWith("Id") ? "uuid" : "string" },
        })),
        responses: defaultResponses(method),
      };
    }
  }

  const spec = {
    openapi: "3.1.0",
    info: {
      title: "ARCTOS GRC Platform API",
      version: "1.0.0",
      description:
        "Auto-generated OpenAPI skeleton from file-system structure of apps/web/src/app/api/v1/.\n" +
        "NOT a complete spec: request/response schemas need Zod→JSON-Schema adapter (see docs/ADR-TBD).\n" +
        "Generated by scripts/generate-openapi.mjs.",
    },
    servers: [
      { url: "https://arctos.charliehund.de", description: "Production" },
      { url: "http://localhost:3000", description: "Local dev" },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Session cookie-based auth via Auth.js. Values in security[].bearerAuth[] are REQUIRED role names.",
        },
      },
    },
    paths,
  };

  await mkdir(join(ROOT, "docs"), { recursive: true });
  await writeFile(OUT, toYaml(spec));
  console.log(`→ Wrote ${OUT}`);
  console.log(`  Paths: ${Object.keys(paths).length}`);
  console.log(`  Method-combos: ${Object.values(paths).reduce((s, o) => s + Object.keys(o).length, 0)}`);
}

function tagFor(path) {
  // /api/v1/audit-mgmt/audits/... -> audit-mgmt
  const m = path.match(/^\/api\/v1\/([^/]+)/);
  return m?.[1] ?? "misc";
}

function defaultResponses(method) {
  if (method === "get") {
    return {
      "200": { description: "OK", content: { "application/json": { schema: { type: "object" } } } },
      "401": { description: "Unauthorized" },
      "403": { description: "Forbidden" },
      "404": { description: "Not Found" },
    };
  }
  if (method === "delete") {
    return {
      "204": { description: "Deleted" },
      "401": { description: "Unauthorized" },
      "403": { description: "Forbidden" },
      "404": { description: "Not Found" },
    };
  }
  return {
    "201": { description: "Created / Updated", content: { "application/json": { schema: { type: "object" } } } },
    "200": { description: "OK" },
    "401": { description: "Unauthorized" },
    "403": { description: "Forbidden" },
    "422": { description: "Validation failed", content: { "application/json": { schema: { type: "object", properties: { error: { type: "string" }, details: { type: "object" } } } } } },
  };
}

function toYaml(obj, indent = 0) {
  const pad = "  ".repeat(indent);
  if (obj === null || obj === undefined) return "null";
  if (typeof obj === "string") {
    if (/[:#\n\r]/.test(obj) || obj === "") return JSON.stringify(obj);
    return obj;
  }
  if (typeof obj === "number" || typeof obj === "boolean") return String(obj);
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    return "\n" + obj.map((item) => `${pad}- ${toYamlInline(item, indent + 1)}`).join("\n");
  }
  if (typeof obj === "object") {
    const keys = Object.keys(obj);
    if (keys.length === 0) return "{}";
    return "\n" + keys
      .map((k) => {
        const v = obj[k];
        const key = /^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(k) ? k : JSON.stringify(k);
        if (v === null || typeof v !== "object" || (Array.isArray(v) && v.length === 0)) {
          return `${pad}${key}: ${toYamlInline(v, indent + 1)}`;
        }
        return `${pad}${key}:${toYaml(v, indent + 1)}`;
      })
      .join("\n");
  }
  return JSON.stringify(obj);
}

function toYamlInline(obj, indent = 0) {
  if (obj === null || obj === undefined) return "null";
  if (typeof obj === "string") {
    if (/[:#\n\r]/.test(obj) || obj === "") return JSON.stringify(obj);
    return obj;
  }
  if (typeof obj === "number" || typeof obj === "boolean") return String(obj);
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    return toYaml(obj, indent);
  }
  if (typeof obj === "object") {
    return toYaml(obj, indent);
  }
  return JSON.stringify(obj);
}

main().catch((e) => { console.error(e); process.exit(1); });
