import { getRequestConfig } from "next-intl/server";
import { cookies } from "next/headers";

const SUPPORTED_LOCALES = ["de", "en"] as const;
const DEFAULT_LOCALE = "de";
const LOCALE_COOKIE = "NEXT_LOCALE";

/**
 * Load all namespace files individually (fallback for dev mode when
 * the pre-built bundle doesn't exist, preserving hot-reload on individual files).
 */
async function loadIndividualFiles(locale: string) {
  const namespaceMap: Array<[string, string]> = [
    ["common", "common"],
    ["identity", "identity"],
    ["import", "import"],
    ["dashboard", "dashboard"],
    ["fair", "fair"],
    ["graph", "graph"],
    ["copilot", "copilot"],
    ["automation", "automation"],
    ["reporting", "reporting"],
    ["simulator", "simulator"],
    ["analytics", "analytics"],
    ["benchmarking", "benchmarking"],
    ["predictions", "predictions"],
    ["propagation", "propagation"],
    ["regulatory", "regulatory"],
    ["board-kpi", "boardKpi"],
    ["erm-advanced", "ermAdvanced"],
    ["erm-evaluation", "ermEvaluation"],
    ["ics-advanced", "icsAdvanced"],
    ["audit-advanced", "auditAdvanced"],
    ["bcms-advanced", "bcmsAdvanced"],
    ["dpms-advanced", "dpmsAdvanced"],
    ["tprm-advanced", "tprmAdvanced"],
    ["esg-advanced", "esgAdvanced"],
    ["bpm-advanced", "bpmAdvanced"],
    ["bpm-derived", "bpmDerived"],
    ["whistleblowing-advanced", "whistleblowingAdvanced"],
    ["platform-advanced", "platformAdvanced"],
    ["eam", "eam"],
    ["eam-dashboards", "eamDashboards"],
    ["eam-data-architecture", "eamDataArchitecture"],
    ["eam-ai", "eamAi"],
    ["eam-catalog", "eamCatalog"],
    ["eam-governance", "eamGovernance"],
    ["connectors", "connectors"],
    ["evidence-review", "evidenceReview"],
    ["control-testing", "controlTesting"],
    ["predictive-risk", "predictiveRisk"],
    ["isms-intelligence", "ismsIntelligence"],
    ["marketplace", "marketplace"],
    ["portals", "portals"],
    ["academy", "academy"],
    ["simulations", "simulations"],
    ["community", "community"],
    ["risk-quantification", "riskQuantification"],
    ["data-sovereignty", "dataSovereignty"],
    ["role-dashboards", "roleDashboards"],
    ["bi-reporting", "biReporting"],
    ["dora", "dora"],
    ["ai-act", "aiAct"],
    ["tax-cms", "taxCms"],
    ["nis2", "nis2"],
    ["cve", "cve"],
    ["certifications", "certifications"],
    ["horizon-scanner", "horizonScanner"],
    ["cert-wizard", "certWizard"],
    ["abac", "abac"],
    ["agents", "agents"],
    ["extensions", "extensions"],
    ["translations", "translations"],
    ["onboarding", "onboarding"],
    ["performance", "performance"],
    ["billing", "billing"],
    ["grc-ux", "grcUx"],
    ["mobile", "mobile"],
    ["developer-portal", "developerPortal"],
    ["attack-paths", "attackPaths"],
    ["correlation", "correlation"],
    ["cci", "cci"],
  ];

  const modules = await Promise.all(
    namespaceMap.map(([file]) =>
      import(`../../messages/${locale}/${file}.json`).catch(() => ({ default: {} }))
    )
  );

  const merged: Record<string, unknown> = {};
  for (let i = 0; i < namespaceMap.length; i++) {
    merged[namespaceMap[i][1]] = modules[i].default;
  }

  // Spread common into root for backward compatibility
  return { ...(merged.common as Record<string, unknown>), ...merged };
}

/**
 * Load messages for a locale. Tries the pre-built single bundle first
 * (generated by scripts/build-messages.ts). Falls back to loading
 * individual namespace files for dev mode hot-reload.
 */
async function loadMessages(locale: string) {
  try {
    const bundle = (await import(`../../messages/${locale}.json`)).default;
    return bundle;
  } catch {
    // Pre-built bundle not found — load individual files (dev mode)
    return await loadIndividualFiles(locale);
  }
}

export default getRequestConfig(async () => {
  let locale: string = DEFAULT_LOCALE;
  try {
    const cookieStore = await cookies();
    const stored = cookieStore.get(LOCALE_COOKIE)?.value;
    if (stored && SUPPORTED_LOCALES.includes(stored as typeof SUPPORTED_LOCALES[number])) {
      locale = stored;
    }
  } catch {
    // cookies() may throw in edge cases (e.g., static generation); fall back to default
  }

  return {
    locale,
    messages: await loadMessages(locale),
  };
});
