-- Sprint 63: Cloud Infrastructure Connectors
-- Migration 942: Seed AWS test definitions (25 tests)

INSERT INTO connector_test_definition (test_key, connector_type, provider_key, name, description, category, severity, framework_mappings, test_logic) VALUES
  ('aws_iam_root_mfa', 'aws', 'aws_iam', 'Root Account MFA Enabled', 'Verify that the root account has MFA enabled', 'iam', 'critical', '[{"framework":"ISO27001","controlId":"A.9.4.2"},{"framework":"NIST_CSF","controlId":"PR.AC-7"}]', '{"apiCalls":["iam:GetAccountSummary"],"evaluationRules":[{"field":"AccountMFAEnabled","op":"=","value":1}]}'),
  ('aws_iam_password_policy', 'aws', 'aws_iam', 'IAM Password Policy', 'Check IAM password policy meets minimum requirements', 'iam', 'high', '[{"framework":"ISO27001","controlId":"A.9.4.3"}]', '{"apiCalls":["iam:GetAccountPasswordPolicy"],"evaluationRules":[{"field":"MinimumPasswordLength","op":">=","value":14}]}'),
  ('aws_iam_unused_credentials', 'aws', 'aws_iam', 'Unused IAM Credentials', 'Identify credentials not used in 90 days', 'iam', 'medium', '[{"framework":"ISO27001","controlId":"A.9.2.6"}]', '{"apiCalls":["iam:GenerateCredentialReport"],"evaluationRules":[{"field":"lastUsedDays","op":"<","value":90}]}'),
  ('aws_iam_user_mfa', 'aws', 'aws_iam', 'IAM Users MFA', 'All IAM users with console access have MFA', 'iam', 'high', '[{"framework":"ISO27001","controlId":"A.9.4.2"}]', '{"apiCalls":["iam:ListUsers","iam:ListMFADevices"],"evaluationRules":[{"field":"mfaActive","op":"=","value":true}]}'),
  ('aws_iam_access_keys_rotation', 'aws', 'aws_iam', 'Access Key Rotation', 'Access keys rotated within 90 days', 'iam', 'medium', '[{"framework":"ISO27001","controlId":"A.9.2.4"}]', '{"apiCalls":["iam:ListAccessKeys"],"evaluationRules":[{"field":"keyAgeDays","op":"<","value":90}]}'),
  ('aws_s3_encryption', 'aws', 'aws_s3', 'S3 Bucket Encryption', 'All S3 buckets have default encryption', 'encryption', 'high', '[{"framework":"ISO27001","controlId":"A.10.1.1"}]', '{"apiCalls":["s3:GetBucketEncryption"],"evaluationRules":[{"field":"encryptionEnabled","op":"=","value":true}]}'),
  ('aws_s3_public_access', 'aws', 'aws_s3', 'S3 Public Access Block', 'S3 public access block enabled', 'data_protection', 'critical', '[{"framework":"ISO27001","controlId":"A.13.1.3"}]', '{"apiCalls":["s3:GetPublicAccessBlock"],"evaluationRules":[{"field":"blockPublicAccess","op":"=","value":true}]}'),
  ('aws_s3_versioning', 'aws', 'aws_s3', 'S3 Bucket Versioning', 'S3 buckets have versioning enabled', 'data_protection', 'medium', '[{"framework":"ISO27001","controlId":"A.12.3.1"}]', '{"apiCalls":["s3:GetBucketVersioning"],"evaluationRules":[{"field":"versioningEnabled","op":"=","value":true}]}'),
  ('aws_cloudtrail_enabled', 'aws', 'aws_cloudtrail', 'CloudTrail Enabled', 'CloudTrail is enabled in all regions', 'logging', 'critical', '[{"framework":"ISO27001","controlId":"A.12.4.1"},{"framework":"NIST_CSF","controlId":"DE.AE-3"}]', '{"apiCalls":["cloudtrail:DescribeTrails"],"evaluationRules":[{"field":"isMultiRegion","op":"=","value":true}]}'),
  ('aws_cloudtrail_log_validation', 'aws', 'aws_cloudtrail', 'CloudTrail Log Validation', 'CloudTrail log file validation enabled', 'logging', 'high', '[]', '{"apiCalls":["cloudtrail:DescribeTrails"],"evaluationRules":[{"field":"logFileValidationEnabled","op":"=","value":true}]}'),
  ('aws_config_enabled', 'aws', 'aws_config', 'Config Service Enabled', 'AWS Config is recording in all regions', 'monitoring', 'high', '[{"framework":"ISO27001","controlId":"A.12.4.1"}]', '{"apiCalls":["config:DescribeConfigurationRecorders"],"evaluationRules":[{"field":"isRecording","op":"=","value":true}]}'),
  ('aws_sg_unrestricted_ssh', 'aws', 'aws_ec2', 'Security Groups SSH', 'No unrestricted SSH access (0.0.0.0/0:22)', 'network', 'critical', '[{"framework":"ISO27001","controlId":"A.13.1.1"}]', '{"apiCalls":["ec2:DescribeSecurityGroups"],"evaluationRules":[{"field":"unrestrictedSSH","op":"=","value":false}]}'),
  ('aws_sg_unrestricted_rdp', 'aws', 'aws_ec2', 'Security Groups RDP', 'No unrestricted RDP access (0.0.0.0/0:3389)', 'network', 'critical', '[]', '{"apiCalls":["ec2:DescribeSecurityGroups"],"evaluationRules":[{"field":"unrestrictedRDP","op":"=","value":false}]}'),
  ('aws_kms_rotation', 'aws', 'aws_kms', 'KMS Key Rotation', 'KMS CMK automatic rotation enabled', 'encryption', 'high', '[{"framework":"ISO27001","controlId":"A.10.1.2"}]', '{"apiCalls":["kms:GetKeyRotationStatus"],"evaluationRules":[{"field":"keyRotationEnabled","op":"=","value":true}]}'),
  ('aws_guardduty_enabled', 'aws', 'aws_guardduty', 'GuardDuty Enabled', 'GuardDuty is enabled in all regions', 'monitoring', 'high', '[{"framework":"ISO27001","controlId":"A.12.6.1"}]', '{"apiCalls":["guardduty:ListDetectors"],"evaluationRules":[{"field":"detectorsActive","op":">","value":0}]}'),
  ('aws_vpc_flow_logs', 'aws', 'aws_vpc', 'VPC Flow Logs', 'VPC Flow Logs enabled for all VPCs', 'logging', 'high', '[{"framework":"ISO27001","controlId":"A.13.1.1"}]', '{"apiCalls":["ec2:DescribeFlowLogs","ec2:DescribeVpcs"],"evaluationRules":[{"field":"flowLogsEnabled","op":"=","value":true}]}'),
  ('aws_rds_encryption', 'aws', 'aws_rds', 'RDS Encryption at Rest', 'All RDS instances encrypted at rest', 'encryption', 'high', '[{"framework":"ISO27001","controlId":"A.10.1.1"}]', '{"apiCalls":["rds:DescribeDBInstances"],"evaluationRules":[{"field":"storageEncrypted","op":"=","value":true}]}'),
  ('aws_rds_public_access', 'aws', 'aws_rds', 'RDS Public Access', 'No RDS instances publicly accessible', 'network', 'critical', '[]', '{"apiCalls":["rds:DescribeDBInstances"],"evaluationRules":[{"field":"publiclyAccessible","op":"=","value":false}]}'),
  ('aws_rds_backup', 'aws', 'aws_rds', 'RDS Automated Backups', 'RDS automated backups enabled', 'data_protection', 'high', '[{"framework":"ISO27001","controlId":"A.12.3.1"}]', '{"apiCalls":["rds:DescribeDBInstances"],"evaluationRules":[{"field":"backupRetentionPeriod","op":">","value":0}]}'),
  ('aws_ebs_encryption', 'aws', 'aws_ec2', 'EBS Default Encryption', 'EBS default encryption enabled', 'encryption', 'medium', '[]', '{"apiCalls":["ec2:GetEbsEncryptionByDefault"],"evaluationRules":[{"field":"ebsEncryptionByDefault","op":"=","value":true}]}'),
  ('aws_lambda_public', 'aws', 'aws_lambda', 'Lambda Public Access', 'No Lambda functions with public access', 'access_control', 'high', '[]', '{"apiCalls":["lambda:ListFunctions","lambda:GetPolicy"],"evaluationRules":[{"field":"publicAccess","op":"=","value":false}]}'),
  ('aws_ecr_scan', 'aws', 'aws_ecr', 'ECR Image Scanning', 'ECR image scanning on push enabled', 'configuration', 'medium', '[]', '{"apiCalls":["ecr:DescribeRepositories"],"evaluationRules":[{"field":"scanOnPush","op":"=","value":true}]}'),
  ('aws_secrets_rotation', 'aws', 'aws_secretsmanager', 'Secrets Rotation', 'Secrets Manager automatic rotation enabled', 'encryption', 'medium', '[]', '{"apiCalls":["secretsmanager:ListSecrets"],"evaluationRules":[{"field":"rotationEnabled","op":"=","value":true}]}'),
  ('aws_waf_enabled', 'aws', 'aws_waf', 'WAF Enabled', 'WAF enabled on public-facing resources', 'network', 'high', '[]', '{"apiCalls":["wafv2:ListWebACLs"],"evaluationRules":[{"field":"webACLCount","op":">","value":0}]}'),
  ('aws_account_alternate_contacts', 'aws', 'aws_account', 'Alternate Contacts', 'Security alternate contact configured', 'configuration', 'low', '[]', '{"apiCalls":["account:GetAlternateContact"],"evaluationRules":[{"field":"securityContact","op":"!=","value":null}]}')
ON CONFLICT (test_key) DO NOTHING;
