import { db, riskPredictionModel, riskPrediction } from "@grc/db";
import { generatePredictionsSchema } from "@grc/shared";
import { eq, and } from "drizzle-orm";
import { withAuth, withAuditContext } from "@/lib/api";

// POST /api/v1/predictive-risk/models/:id/predict — Generate predictions
export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const ctx = await withAuth("admin", "risk_manager");
  if (ctx instanceof Response) return ctx;

  const { id } = await params;
  const body = generatePredictionsSchema.safeParse(await req.json());
  if (!body.success) {
    return Response.json(
      { error: "Validation failed", details: body.error.flatten() },
      { status: 422 },
    );
  }

  const [model] = await db
    .select()
    .from(riskPredictionModel)
    .where(
      and(
        eq(riskPredictionModel.id, id),
        eq(riskPredictionModel.orgId, ctx.orgId),
      ),
    );

  if (!model)
    return Response.json({ error: "Model not found" }, { status: 404 });
  if (model.status !== "active") {
    return Response.json(
      { error: "Model must be active to generate predictions" },
      { status: 400 },
    );
  }

  // In production, predictions would be generated by ML pipeline
  return Response.json(
    {
      data: {
        modelId: id,
        status: "queued",
        horizonDays: body.data.horizonDays,
      },
    },
    { status: 202 },
  );
}
