// Shared styles and layout for all ARCTOS email templates
// Import this in every template to maintain consistent branding

import { Html, Head, Body, Container, Section, Text, Button, Hr, Preview, Font } from "@react-email/components";
import * as React from "react";

export const styles = {
  body: { backgroundColor: "#f4f4f5", fontFamily: "Arial, Helvetica, sans-serif", margin: "0" as const, padding: "0" as const },
  container: { backgroundColor: "#ffffff", borderRadius: "8px", margin: "40px auto", maxWidth: "600px", overflow: "hidden" as const },
  header: { backgroundColor: "#0f172a", padding: "24px 32px", textAlign: "center" as const },
  logo: { color: "#ffffff", fontSize: "28px", fontWeight: "700" as const, letterSpacing: "3px", margin: "0" },
  logoSubtitle: { color: "#94a3b8", fontSize: "11px", letterSpacing: "1px", margin: "4px 0 0 0", textTransform: "uppercase" as const },
  hr: { borderColor: "#e4e4e7", borderTop: "1px solid #e4e4e7", margin: "0" },
  content: { padding: "32px" },
  heading: { color: "#0f172a", fontSize: "22px", fontWeight: "600" as const, margin: "0 0 16px 0" },
  text: { color: "#374151", fontSize: "15px", lineHeight: "24px", margin: "0 0 12px 0" },
  card: { backgroundColor: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "6px", margin: "20px 0", padding: "20px" },
  cardLabel: { color: "#64748b", fontSize: "12px", fontWeight: "600" as const, letterSpacing: "0.5px", margin: "12px 0 2px 0", textTransform: "uppercase" as const },
  cardValue: { color: "#0f172a", fontSize: "15px", fontWeight: "500" as const, margin: "0 0 8px 0" },
  urgentBanner: { backgroundColor: "#fef2f2", border: "1px solid #fecaca", borderRadius: "6px", margin: "20px 0", padding: "16px 20px" },
  urgentText: { color: "#dc2626", fontSize: "14px", fontWeight: "600" as const, margin: "0" },
  ctaSection: { margin: "24px 0 0 0", textAlign: "center" as const },
  button: { backgroundColor: "#2563eb", borderRadius: "6px", color: "#ffffff", display: "inline-block" as const, fontSize: "15px", fontWeight: "600" as const, padding: "12px 32px", textDecoration: "none" },
  buttonDanger: { backgroundColor: "#dc2626", borderRadius: "6px", color: "#ffffff", display: "inline-block" as const, fontSize: "15px", fontWeight: "600" as const, padding: "12px 32px", textDecoration: "none" },
  footer: { padding: "20px 32px", textAlign: "center" as const },
  footerText: { color: "#94a3b8", fontSize: "12px", lineHeight: "18px", margin: "0 0 8px 0" },
  footerBrand: { color: "#94a3b8", fontSize: "11px", letterSpacing: "1px", margin: "0", textTransform: "uppercase" as const },
  badge: { borderRadius: "4px", color: "#ffffff", display: "inline-block" as const, fontSize: "12px", fontWeight: "600" as const, margin: "4px 0 0 0", padding: "3px 10px" },
};

export function EmailLayout({ lang, preview, children, orgName }: { lang: "de" | "en"; preview: string; children: React.ReactNode; orgName?: string }) {
  const footerMsg = lang === "de" ? "Diese E-Mail wurde automatisch von ARCTOS generiert." : "This email was automatically generated by ARCTOS.";
  return (
    <Html lang={lang}>
      <Head><Font fontFamily="Arial" fallbackFontFamily="Helvetica" fontWeight={400} fontStyle="normal" /></Head>
      <Preview>{preview}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
            <Text style={styles.logo}>ARCTOS</Text>
            <Text style={styles.logoSubtitle}>Audit, Risk, Compliance &amp; Trust</Text>
          </Section>
          <Hr style={styles.hr} />
          <Section style={styles.content}>{children}</Section>
          <Hr style={styles.hr} />
          <Section style={styles.footer}>
            {orgName && <Text style={{ ...styles.footerText, fontWeight: "500" as const }}>{orgName}</Text>}
            <Text style={styles.footerText}>{footerMsg}</Text>
            <Text style={styles.footerBrand}>ARCTOS GRC Platform</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}
