// GenericNotification.tsx
//
// [ARCTOS-FULL-2026-08-31 / WP9 · S10-03] The shared layout behind the 65
// template keys that had no renderer at all. It is not a placeholder: it
// renders the real notification content (title, message, entity, due date)
// plus a severity accent and a working deep link, in DE and EN. What it
// deliberately does NOT do is invent content — a field that is absent from
// the notification simply does not appear.

import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Preview,
  Font,
} from "@react-email/components";
import * as React from "react";
import type { EmailSeverity } from "../template-registry";

export interface GenericNotificationProps {
  lang: "de" | "en";
  /** Subject-line stem from the registry, e.g. "Richtlinie überfällig". */
  headline: string;
  severity: EmailSeverity;
  /** The notification's own title. */
  title: string;
  /** The notification's own message body, if it has one. */
  message?: string;
  /** Optional labelled facts, rendered as a definition card. */
  facts?: Array<{ label: string; value: string }>;
  actionUrl?: string;
  recipientName?: string;
  orgName?: string;
}

const t = {
  de: {
    greeting: (n?: string) => (n ? `Hallo ${n},` : "Hallo,"),
    intro: "die ARCTOS-Plattform hat folgenden Vorgang für Sie erfasst:",
    cta: "In ARCTOS öffnen",
    footer:
      "Diese E-Mail wurde automatisch von ARCTOS generiert. Bitte antworten Sie nicht auf diese E-Mail.",
    severity: {
      info: "Information",
      action: "Handlung erforderlich",
      warning: "Frist überschritten",
      critical: "Gesetzliche Frist",
    } as Record<EmailSeverity, string>,
  },
  en: {
    greeting: (n?: string) => (n ? `Hello ${n},` : "Hello,"),
    intro: "The ARCTOS platform recorded the following item for you:",
    cta: "Open in ARCTOS",
    footer:
      "This email was automatically generated by ARCTOS. Please do not reply to this email.",
    severity: {
      info: "Information",
      action: "Action required",
      warning: "Overdue",
      critical: "Statutory deadline",
    } as Record<EmailSeverity, string>,
  },
};

const ACCENT: Record<
  EmailSeverity,
  { bg: string; border: string; fg: string }
> = {
  info: { bg: "#f1f5f9", border: "#cbd5e1", fg: "#334155" },
  action: { bg: "#eff6ff", border: "#bfdbfe", fg: "#1e40af" },
  warning: { bg: "#fffbeb", border: "#fcd34d", fg: "#92400e" },
  critical: { bg: "#fef2f2", border: "#fca5a5", fg: "#991b1b" },
};

/**
 * [ARCTOS-FULL-2026-08-31 · OP-066] `data` kommt aus `notification.template_data`
 * — einer JSONB-Spalte. Dort steht, was die Cron-Jobs hineingeschrieben haben,
 * und das ist nicht zwingend eine Zeichenkette. `(data.x as string)` war eine
 * Behauptung, keine Prüfung: bei einer Zahl wanderte sie unverändert in die
 * Betreffzeile, bei einem Objekt "[object Object]", und eine Zeichenkette mit
 * CR/LF haette die Betreffzeile verlassen und eigene Kopfzeilen aufgemacht.
 * Der Fund stammt aus dem Test, der zu dieser Datei fehlte.
 */
function asSubjectText(value: unknown): string {
  if (typeof value !== "string") return "";
  // Kopfzeilen sind einzeilig. Alles, was umbricht, wird zu einem Leerzeichen.
  return value.replace(/[\r\n]+/g, " ").trim();
}

export function getSubject(
  data: Record<string, unknown>,
  lang: "de" | "en",
): string {
  const headline = asSubjectText(data.__headline);
  const title =
    asSubjectText(data.notificationTitle) || asSubjectText(data.title);
  if (headline && title) return `${headline}: ${title}`;
  return (
    headline ||
    title ||
    (lang === "de" ? "ARCTOS-Benachrichtigung" : "ARCTOS notification")
  );
}

export const GenericNotification: React.FC<GenericNotificationProps> = ({
  lang,
  headline,
  severity,
  title,
  message,
  facts,
  actionUrl,
  recipientName,
  orgName,
}) => {
  const tr = t[lang];
  const accent = ACCENT[severity];

  return (
    <Html lang={lang}>
      <Head>
        <Font
          fontFamily="Arial"
          fallbackFontFamily="Helvetica"
          fontWeight={400}
          fontStyle="normal"
        />
      </Head>
      <Preview>{`${headline}: ${title}`}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
            <Text style={styles.logo}>ARCTOS</Text>
            <Text style={styles.logoSubtitle}>
              Audit, Risk, Compliance &amp; Trust
            </Text>
          </Section>

          <Hr style={styles.hr} />

          <Section style={styles.content}>
            <Text
              style={{
                ...styles.badge,
                backgroundColor: accent.bg,
                border: `1px solid ${accent.border}`,
                color: accent.fg,
              }}
            >
              {tr.severity[severity]}
            </Text>

            <Text style={styles.heading}>{headline}</Text>
            <Text style={styles.text}>{tr.greeting(recipientName)}</Text>
            <Text style={styles.text}>{tr.intro}</Text>

            <Section
              style={{
                ...styles.card,
                backgroundColor: accent.bg,
                border: `1px solid ${accent.border}`,
              }}
            >
              <Text style={styles.cardValue}>{title}</Text>
              {message ? <Text style={styles.text}>{message}</Text> : null}
              {(facts ?? []).map((f) => (
                <React.Fragment key={f.label}>
                  <Text style={styles.cardLabel}>{f.label}</Text>
                  <Text style={styles.cardValue}>{f.value}</Text>
                </React.Fragment>
              ))}
            </Section>

            {actionUrl ? (
              <Section style={styles.ctaSection}>
                <Button style={styles.button} href={actionUrl}>
                  {tr.cta}
                </Button>
              </Section>
            ) : null}
          </Section>

          <Hr style={styles.hr} />

          <Section style={styles.footer}>
            {orgName ? <Text style={styles.footerOrg}>{orgName}</Text> : null}
            <Text style={styles.footerText}>{tr.footer}</Text>
            <Text style={styles.footerBrand}>ARCTOS GRC Platform</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

const styles = {
  body: {
    backgroundColor: "#f4f4f5",
    fontFamily: "Arial, Helvetica, sans-serif",
    margin: "0" as const,
    padding: "0" as const,
  },
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    margin: "40px auto",
    maxWidth: "600px",
    overflow: "hidden" as const,
  },
  header: {
    backgroundColor: "#0f172a",
    padding: "24px 32px",
    textAlign: "center" as const,
  },
  logo: {
    color: "#ffffff",
    fontSize: "28px",
    fontWeight: "700" as const,
    letterSpacing: "3px",
    margin: "0",
  },
  logoSubtitle: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "4px 0 0 0",
    textTransform: "uppercase" as const,
  },
  hr: { borderColor: "#e4e4e7", borderTop: "1px solid #e4e4e7", margin: "0" },
  content: { padding: "32px" },
  badge: {
    borderRadius: "4px",
    display: "inline-block" as const,
    fontSize: "11px",
    fontWeight: "700" as const,
    letterSpacing: "0.5px",
    margin: "0 0 12px 0",
    padding: "4px 10px",
    textTransform: "uppercase" as const,
  },
  heading: {
    color: "#0f172a",
    fontSize: "22px",
    fontWeight: "600" as const,
    margin: "0 0 16px 0",
  },
  text: {
    color: "#374151",
    fontSize: "15px",
    lineHeight: "24px",
    margin: "0 0 12px 0",
  },
  card: {
    borderRadius: "6px",
    margin: "20px 0",
    padding: "20px",
  },
  cardLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "600" as const,
    letterSpacing: "0.5px",
    margin: "12px 0 2px 0",
    textTransform: "uppercase" as const,
  },
  cardValue: {
    color: "#0f172a",
    fontSize: "15px",
    fontWeight: "500" as const,
    margin: "0 0 8px 0",
  },
  ctaSection: { margin: "24px 0 0 0", textAlign: "center" as const },
  button: {
    backgroundColor: "#2563eb",
    borderRadius: "6px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "15px",
    fontWeight: "600" as const,
    padding: "12px 32px",
    textDecoration: "none",
  },
  footer: { padding: "20px 32px", textAlign: "center" as const },
  footerOrg: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: "500" as const,
    margin: "0 0 4px 0",
  },
  footerText: {
    color: "#94a3b8",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "0 0 8px 0",
  },
  footerBrand: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "0",
    textTransform: "uppercase" as const,
  },
};

export default GenericNotification;
