import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Preview,
  Font,
} from "@react-email/components";
import * as React from "react";

interface NotificationItem {
  type: string;
  title: string;
  timestamp: string;
  url?: string;
}

interface NotificationDigestProps {
  lang: "de" | "en";
  notifications: NotificationItem[];
  platformUrl: string;
  orgName?: string;
  digestDate: string;
}

const typeLabels: Record<string, Record<string, string>> = {
  de: {
    task_assigned: "Aufgabe zugewiesen",
    task_overdue: "Aufgabe überfällig",
    task_reminder: "Aufgabenerinnerung",
    task_completed: "Aufgabe abgeschlossen",
    user_invited: "Einladung",
    risk_created: "Risiko erstellt",
    risk_updated: "Risiko aktualisiert",
    compliance_update: "Compliance-Aktualisierung",
    system: "System",
  },
  en: {
    task_assigned: "Task Assigned",
    task_overdue: "Task Overdue",
    task_reminder: "Task Reminder",
    task_completed: "Task Completed",
    user_invited: "Invitation",
    risk_created: "Risk Created",
    risk_updated: "Risk Updated",
    compliance_update: "Compliance Update",
    system: "System",
  },
};

const typeColors: Record<string, string> = {
  task_assigned: "#2563eb",
  task_overdue: "#dc2626",
  task_reminder: "#ea580c",
  task_completed: "#16a34a",
  user_invited: "#7c3aed",
  risk_created: "#ea580c",
  risk_updated: "#d97706",
  compliance_update: "#0891b2",
  system: "#6b7280",
};

const translations = {
  de: {
    preview: "ARCTOS Tagesübersicht",
    heading: "Tagesübersicht",
    subtitle: (date: string) => `Zusammenfassung für ${date}`,
    totalNotifications: (count: number) =>
      `${count} Benachrichtigung${count !== 1 ? "en" : ""}`,
    noNotifications: "Keine neuen Benachrichtigungen.",
    viewAll: "Alle Benachrichtigungen anzeigen",
    cta: "Plattform öffnen",
    footer:
      "Diese E-Mail wurde automatisch von ARCTOS generiert. Bitte antworten Sie nicht auf diese E-Mail.",
    digestSettings:
      "Sie erhalten diese Zusammenfassung täglich. Sie können dies in Ihren Benachrichtigungseinstellungen ändern.",
  },
  en: {
    preview: "ARCTOS Daily Digest",
    heading: "Daily Digest",
    subtitle: (date: string) => `Summary for ${date}`,
    totalNotifications: (count: number) =>
      `${count} notification${count !== 1 ? "s" : ""}`,
    noNotifications: "No new notifications.",
    viewAll: "View all notifications",
    cta: "Open Platform",
    footer:
      "This email was automatically generated by ARCTOS. Please do not reply to this email.",
    digestSettings:
      "You receive this daily digest. You can change this in your notification settings.",
  },
};

export function getSubject(
  _data: Record<string, unknown>,
  lang: "de" | "en"
): string {
  return lang === "de" ? "ARCTOS Tagesübersicht" : "ARCTOS Daily Digest";
}

export const NotificationDigest: React.FC<NotificationDigestProps> = ({
  lang,
  notifications,
  platformUrl,
  orgName,
  digestDate,
}) => {
  const t = translations[lang];

  // Group notifications by type
  const grouped = notifications.reduce<Record<string, NotificationItem[]>>(
    (acc, notification) => {
      const type = notification.type;
      if (!acc[type]) {
        acc[type] = [];
      }
      acc[type].push(notification);
      return acc;
    },
    {}
  );

  return (
    <Html lang={lang}>
      <Head>
        <Font
          fontFamily="Arial"
          fallbackFontFamily="Helvetica"
          fontWeight={400}
          fontStyle="normal"
        />
      </Head>
      <Preview>{t.preview}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          {/* Header */}
          <Section style={styles.header}>
            <Text style={styles.logo}>ARCTOS</Text>
            <Text style={styles.logoSubtitle}>
              Audit, Risk, Compliance &amp; Trust
            </Text>
          </Section>

          <Hr style={styles.hr} />

          {/* Content */}
          <Section style={styles.content}>
            <Text style={styles.heading}>{t.heading}</Text>
            <Text style={styles.subtitle}>{t.subtitle(digestDate)}</Text>

            {/* Summary Count */}
            <Section style={styles.summaryBanner}>
              <Text style={styles.summaryCount}>
                {t.totalNotifications(notifications.length)}
              </Text>
            </Section>

            {notifications.length === 0 ? (
              <Text style={styles.emptyText}>{t.noNotifications}</Text>
            ) : (
              Object.entries(grouped).map(([type, items]) => (
                <Section key={type} style={styles.groupSection}>
                  <Text style={styles.groupHeader}>
                    <span
                      style={{
                        ...styles.groupDot,
                        backgroundColor: typeColors[type] || "#6b7280",
                      }}
                    />
                    {(typeLabels[lang] || {})[type] || type} ({items.length})
                  </Text>
                  {items.map((item, idx) => (
                    <Section key={idx} style={styles.notificationItem}>
                      <Text style={styles.notificationTitle}>
                        {item.title}
                      </Text>
                      <Text style={styles.notificationTime}>
                        {item.timestamp}
                      </Text>
                    </Section>
                  ))}
                </Section>
              ))
            )}

            <Section style={styles.ctaSection}>
              <Button style={styles.button} href={platformUrl}>
                {t.cta}
              </Button>
            </Section>
          </Section>

          <Hr style={styles.hr} />

          {/* Footer */}
          <Section style={styles.footer}>
            {orgName && <Text style={styles.footerOrg}>{orgName}</Text>}
            <Text style={styles.digestNote}>{t.digestSettings}</Text>
            <Text style={styles.footerText}>{t.footer}</Text>
            <Text style={styles.footerBrand}>
              ARCTOS GRC Platform
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

const styles = {
  body: {
    backgroundColor: "#f4f4f5",
    fontFamily: "Arial, Helvetica, sans-serif",
    margin: "0" as const,
    padding: "0" as const,
  },
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    margin: "40px auto",
    maxWidth: "600px",
    overflow: "hidden" as const,
  },
  header: {
    backgroundColor: "#0f172a",
    padding: "24px 32px",
    textAlign: "center" as const,
  },
  logo: {
    color: "#ffffff",
    fontSize: "28px",
    fontWeight: "700" as const,
    letterSpacing: "3px",
    margin: "0",
  },
  logoSubtitle: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "4px 0 0 0",
    textTransform: "uppercase" as const,
  },
  hr: {
    borderColor: "#e4e4e7",
    borderTop: "1px solid #e4e4e7",
    margin: "0",
  },
  content: {
    padding: "32px",
  },
  heading: {
    color: "#0f172a",
    fontSize: "22px",
    fontWeight: "600" as const,
    margin: "0 0 4px 0",
  },
  subtitle: {
    color: "#64748b",
    fontSize: "14px",
    margin: "0 0 20px 0",
  },
  summaryBanner: {
    backgroundColor: "#f0f9ff",
    border: "1px solid #bae6fd",
    borderRadius: "6px",
    margin: "0 0 24px 0",
    padding: "12px 16px",
    textAlign: "center" as const,
  },
  summaryCount: {
    color: "#0369a1",
    fontSize: "16px",
    fontWeight: "600" as const,
    margin: "0",
  },
  emptyText: {
    color: "#94a3b8",
    fontSize: "15px",
    margin: "20px 0",
    textAlign: "center" as const,
  },
  groupSection: {
    margin: "0 0 20px 0",
  },
  groupHeader: {
    borderBottom: "1px solid #e2e8f0",
    color: "#0f172a",
    fontSize: "14px",
    fontWeight: "600" as const,
    margin: "0 0 8px 0",
    paddingBottom: "6px",
  },
  groupDot: {
    borderRadius: "50%",
    display: "inline-block" as const,
    height: "8px",
    marginRight: "8px",
    width: "8px",
  },
  notificationItem: {
    borderLeft: "3px solid #e2e8f0",
    margin: "0 0 8px 0",
    padding: "6px 0 6px 12px",
  },
  notificationTitle: {
    color: "#374151",
    fontSize: "14px",
    margin: "0 0 2px 0",
  },
  notificationTime: {
    color: "#94a3b8",
    fontSize: "12px",
    margin: "0",
  },
  ctaSection: {
    margin: "24px 0 0 0",
    textAlign: "center" as const,
  },
  button: {
    backgroundColor: "#2563eb",
    borderRadius: "6px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "15px",
    fontWeight: "600" as const,
    padding: "12px 32px",
    textDecoration: "none",
  },
  footer: {
    padding: "20px 32px",
    textAlign: "center" as const,
  },
  footerOrg: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: "500" as const,
    margin: "0 0 4px 0",
  },
  digestNote: {
    color: "#94a3b8",
    fontSize: "11px",
    fontStyle: "italic" as const,
    lineHeight: "16px",
    margin: "0 0 8px 0",
  },
  footerText: {
    color: "#94a3b8",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "0 0 8px 0",
  },
  footerBrand: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "0",
    textTransform: "uppercase" as const,
  },
};

export default NotificationDigest;
