import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Preview,
  Font,
} from "@react-email/components";
import * as React from "react";

interface TaskOverdueProps {
  lang: "de" | "en";
  taskTitle: string;
  dueDate: string;
  daysOverdue: number;
  taskUrl: string;
  orgName?: string;
}

const translations = {
  de: {
    preview: (title: string) => `Aufgabe überfällig: ${title}`,
    heading: "Aufgabe überfällig",
    intro: "Die folgende Aufgabe hat das Fälligkeitsdatum überschritten:",
    task: "Aufgabe",
    originalDueDate: "Ursprüngliches Fälligkeitsdatum",
    daysOverdue: "Tage überfällig",
    urgentNotice:
      "Bitte bearbeiten Sie diese Aufgabe so schnell wie möglich oder wenden Sie sich an Ihren Vorgesetzten.",
    cta: "Aufgabe öffnen",
    footer:
      "Diese E-Mail wurde automatisch von ARCTOS generiert. Bitte antworten Sie nicht auf diese E-Mail.",
  },
  en: {
    preview: (title: string) => `Task overdue: ${title}`,
    heading: "Task Overdue",
    intro: "The following task has passed its due date:",
    task: "Task",
    originalDueDate: "Original Due Date",
    daysOverdue: "Days Overdue",
    urgentNotice:
      "Please complete this task as soon as possible or contact your supervisor.",
    cta: "Open Task",
    footer:
      "This email was automatically generated by ARCTOS. Please do not reply to this email.",
  },
};

export function getSubject(
  data: Record<string, unknown>,
  lang: "de" | "en",
): string {
  const title = (data.taskTitle as string) || "";
  return lang === "de"
    ? `Aufgabe überfällig: ${title}`
    : `Task overdue: ${title}`;
}

export const TaskOverdue: React.FC<TaskOverdueProps> = ({
  lang,
  taskTitle,
  dueDate,
  daysOverdue,
  taskUrl,
  orgName,
}) => {
  const t = translations[lang];

  return (
    <Html lang={lang}>
      <Head>
        <Font
          fontFamily="Arial"
          fallbackFontFamily="Helvetica"
          fontWeight={400}
          fontStyle="normal"
        />
      </Head>
      <Preview>{t.preview(taskTitle)}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          {/* Header */}
          <Section style={styles.header}>
            <Text style={styles.logo}>ARCTOS</Text>
            <Text style={styles.logoSubtitle}>
              Audit, Risk, Compliance &amp; Trust
            </Text>
          </Section>

          <Hr style={styles.hr} />

          {/* Urgent Banner */}
          <Section style={styles.urgentBanner}>
            <Text style={styles.urgentIcon}>!</Text>
          </Section>

          {/* Content */}
          <Section style={styles.content}>
            <Text style={styles.heading}>{t.heading}</Text>
            <Text style={styles.text}>{t.intro}</Text>

            <Section style={styles.card}>
              <Text style={styles.cardLabel}>{t.task}</Text>
              <Text style={styles.cardValue}>{taskTitle}</Text>

              <Text style={styles.cardLabel}>{t.originalDueDate}</Text>
              <Text style={styles.cardValue}>{dueDate}</Text>

              <Text style={styles.cardLabel}>{t.daysOverdue}</Text>
              <Text style={styles.overdueBadge}>
                {daysOverdue} {lang === "de" ? "Tage" : "days"}
              </Text>
            </Section>

            <Section style={styles.noticeSection}>
              <Text style={styles.noticeText}>{t.urgentNotice}</Text>
            </Section>

            <Section style={styles.ctaSection}>
              <Button style={styles.button} href={taskUrl}>
                {t.cta}
              </Button>
            </Section>
          </Section>

          <Hr style={styles.hr} />

          {/* Footer */}
          <Section style={styles.footer}>
            {orgName && <Text style={styles.footerOrg}>{orgName}</Text>}
            <Text style={styles.footerText}>{t.footer}</Text>
            <Text style={styles.footerBrand}>ARCTOS GRC Platform</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

const styles = {
  body: {
    backgroundColor: "#f4f4f5",
    fontFamily: "Arial, Helvetica, sans-serif",
    margin: "0" as const,
    padding: "0" as const,
  },
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    margin: "40px auto",
    maxWidth: "600px",
    overflow: "hidden" as const,
  },
  header: {
    backgroundColor: "#0f172a",
    padding: "24px 32px",
    textAlign: "center" as const,
  },
  logo: {
    color: "#ffffff",
    fontSize: "28px",
    fontWeight: "700" as const,
    letterSpacing: "3px",
    margin: "0",
  },
  logoSubtitle: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "4px 0 0 0",
    textTransform: "uppercase" as const,
  },
  hr: {
    borderColor: "#e4e4e7",
    borderTop: "1px solid #e4e4e7",
    margin: "0",
  },
  urgentBanner: {
    backgroundColor: "#fef2f2",
    borderBottom: "2px solid #dc2626",
    padding: "8px 32px",
    textAlign: "center" as const,
  },
  urgentIcon: {
    color: "#dc2626",
    fontSize: "24px",
    fontWeight: "700" as const,
    margin: "0",
  },
  content: {
    padding: "32px",
  },
  heading: {
    color: "#dc2626",
    fontSize: "22px",
    fontWeight: "600" as const,
    margin: "0 0 16px 0",
  },
  text: {
    color: "#374151",
    fontSize: "15px",
    lineHeight: "24px",
    margin: "0 0 12px 0",
  },
  card: {
    backgroundColor: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "6px",
    margin: "20px 0",
    padding: "20px",
  },
  cardLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "600" as const,
    letterSpacing: "0.5px",
    margin: "12px 0 2px 0",
    textTransform: "uppercase" as const,
  },
  cardValue: {
    color: "#0f172a",
    fontSize: "15px",
    fontWeight: "500" as const,
    margin: "0 0 8px 0",
  },
  overdueBadge: {
    backgroundColor: "#dc2626",
    borderRadius: "4px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "14px",
    fontWeight: "700" as const,
    margin: "4px 0 0 0",
    padding: "4px 12px",
  },
  noticeSection: {
    backgroundColor: "#fffbeb",
    border: "1px solid #fde68a",
    borderRadius: "6px",
    margin: "16px 0",
    padding: "12px 16px",
  },
  noticeText: {
    color: "#92400e",
    fontSize: "14px",
    lineHeight: "20px",
    margin: "0",
  },
  ctaSection: {
    margin: "24px 0 0 0",
    textAlign: "center" as const,
  },
  button: {
    backgroundColor: "#dc2626",
    borderRadius: "6px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "15px",
    fontWeight: "600" as const,
    padding: "12px 32px",
    textDecoration: "none",
  },
  footer: {
    padding: "20px 32px",
    textAlign: "center" as const,
  },
  footerOrg: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: "500" as const,
    margin: "0 0 4px 0",
  },
  footerText: {
    color: "#94a3b8",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "0 0 8px 0",
  },
  footerBrand: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "0",
    textTransform: "uppercase" as const,
  },
};

export default TaskOverdue;
