import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Preview,
  Font,
} from "@react-email/components";
import * as React from "react";

interface TaskAssignedProps {
  lang: "de" | "en";
  taskTitle: string;
  taskDescription?: string;
  assigneeName: string;
  dueDate: string;
  priority: string;
  taskUrl: string;
  orgName?: string;
}

const translations = {
  de: {
    preview: (title: string) => `Neue Aufgabe zugewiesen: ${title}`,
    heading: "Neue Aufgabe zugewiesen",
    greeting: (name: string) => `Hallo ${name},`,
    intro: "Ihnen wurde eine neue Aufgabe zugewiesen:",
    task: "Aufgabe",
    description: "Beschreibung",
    dueDate: "Fälligkeitsdatum",
    priority: "Priorität",
    cta: "Aufgabe öffnen",
    footer:
      "Diese E-Mail wurde automatisch von ARCTOS generiert. Bitte antworten Sie nicht auf diese E-Mail.",
    priorityLabels: {
      low: "Niedrig",
      medium: "Mittel",
      high: "Hoch",
      critical: "Kritisch",
    } as Record<string, string>,
  },
  en: {
    preview: (title: string) => `New task assigned: ${title}`,
    heading: "New Task Assigned",
    greeting: (name: string) => `Hello ${name},`,
    intro: "You have been assigned a new task:",
    task: "Task",
    description: "Description",
    dueDate: "Due Date",
    priority: "Priority",
    cta: "Open Task",
    footer:
      "This email was automatically generated by ARCTOS. Please do not reply to this email.",
    priorityLabels: {
      low: "Low",
      medium: "Medium",
      high: "High",
      critical: "Critical",
    } as Record<string, string>,
  },
};

const priorityColors: Record<string, string> = {
  low: "#6b7280",
  medium: "#2563eb",
  high: "#ea580c",
  critical: "#dc2626",
};

export function getSubject(
  data: Record<string, unknown>,
  lang: "de" | "en",
): string {
  const title = (data.taskTitle as string) || "";
  return lang === "de"
    ? `Neue Aufgabe zugewiesen: ${title}`
    : `New task assigned: ${title}`;
}

export const TaskAssigned: React.FC<TaskAssignedProps> = ({
  lang,
  taskTitle,
  taskDescription,
  assigneeName,
  dueDate,
  priority,
  taskUrl,
  orgName,
}) => {
  const t = translations[lang];
  const priorityLabel = t.priorityLabels[priority] || priority;
  const priorityColor = priorityColors[priority] || "#6b7280";

  return (
    <Html lang={lang}>
      <Head>
        <Font
          fontFamily="Arial"
          fallbackFontFamily="Helvetica"
          fontWeight={400}
          fontStyle="normal"
        />
      </Head>
      <Preview>{t.preview(taskTitle)}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          {/* Header */}
          <Section style={styles.header}>
            <Text style={styles.logo}>ARCTOS</Text>
            <Text style={styles.logoSubtitle}>
              Audit, Risk, Compliance &amp; Trust
            </Text>
          </Section>

          <Hr style={styles.hr} />

          {/* Content */}
          <Section style={styles.content}>
            <Text style={styles.heading}>{t.heading}</Text>
            <Text style={styles.text}>{t.greeting(assigneeName)}</Text>
            <Text style={styles.text}>{t.intro}</Text>

            <Section style={styles.card}>
              <Text style={styles.cardLabel}>{t.task}</Text>
              <Text style={styles.cardValue}>{taskTitle}</Text>

              {taskDescription && (
                <>
                  <Text style={styles.cardLabel}>{t.description}</Text>
                  <Text style={styles.cardValueLight}>
                    {taskDescription.length > 200
                      ? `${taskDescription.substring(0, 200)}...`
                      : taskDescription}
                  </Text>
                </>
              )}

              <Text style={styles.cardLabel}>{t.dueDate}</Text>
              <Text style={styles.cardValue}>{dueDate}</Text>

              <Text style={styles.cardLabel}>{t.priority}</Text>
              <Text
                style={{
                  ...styles.badge,
                  backgroundColor: priorityColor,
                }}
              >
                {priorityLabel}
              </Text>
            </Section>

            <Section style={styles.ctaSection}>
              <Button style={styles.button} href={taskUrl}>
                {t.cta}
              </Button>
            </Section>
          </Section>

          <Hr style={styles.hr} />

          {/* Footer */}
          <Section style={styles.footer}>
            {orgName && <Text style={styles.footerOrg}>{orgName}</Text>}
            <Text style={styles.footerText}>{t.footer}</Text>
            <Text style={styles.footerBrand}>ARCTOS GRC Platform</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

const styles = {
  body: {
    backgroundColor: "#f4f4f5",
    fontFamily: "Arial, Helvetica, sans-serif",
    margin: "0" as const,
    padding: "0" as const,
  },
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    margin: "40px auto",
    maxWidth: "600px",
    overflow: "hidden" as const,
  },
  header: {
    backgroundColor: "#0f172a",
    padding: "24px 32px",
    textAlign: "center" as const,
  },
  logo: {
    color: "#ffffff",
    fontSize: "28px",
    fontWeight: "700" as const,
    letterSpacing: "3px",
    margin: "0",
  },
  logoSubtitle: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "4px 0 0 0",
    textTransform: "uppercase" as const,
  },
  hr: {
    borderColor: "#e4e4e7",
    borderTop: "1px solid #e4e4e7",
    margin: "0",
  },
  content: {
    padding: "32px",
  },
  heading: {
    color: "#0f172a",
    fontSize: "22px",
    fontWeight: "600" as const,
    margin: "0 0 16px 0",
  },
  text: {
    color: "#374151",
    fontSize: "15px",
    lineHeight: "24px",
    margin: "0 0 12px 0",
  },
  card: {
    backgroundColor: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    margin: "20px 0",
    padding: "20px",
  },
  cardLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "600" as const,
    letterSpacing: "0.5px",
    margin: "12px 0 2px 0",
    textTransform: "uppercase" as const,
  },
  cardValue: {
    color: "#0f172a",
    fontSize: "15px",
    fontWeight: "500" as const,
    margin: "0 0 8px 0",
  },
  cardValueLight: {
    color: "#475569",
    fontSize: "14px",
    margin: "0 0 8px 0",
  },
  badge: {
    borderRadius: "4px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "12px",
    fontWeight: "600" as const,
    margin: "4px 0 0 0",
    padding: "3px 10px",
  },
  ctaSection: {
    margin: "24px 0 0 0",
    textAlign: "center" as const,
  },
  button: {
    backgroundColor: "#2563eb",
    borderRadius: "6px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "15px",
    fontWeight: "600" as const,
    padding: "12px 32px",
    textDecoration: "none",
  },
  footer: {
    padding: "20px 32px",
    textAlign: "center" as const,
  },
  footerOrg: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: "500" as const,
    margin: "0 0 4px 0",
  },
  footerText: {
    color: "#94a3b8",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "0 0 8px 0",
  },
  footerBrand: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "0",
    textTransform: "uppercase" as const,
  },
};

export default TaskAssigned;
