import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Preview,
  Font,
} from "@react-email/components";
import * as React from "react";

interface UserInvitedProps {
  lang: "de" | "en";
  orgName: string;
  roleName: string;
  inviterName: string;
  acceptUrl: string;
}

const roleLabels: Record<string, Record<string, string>> = {
  de: {
    admin: "Administrator",
    risk_manager: "Risikomanager",
    control_owner: "Kontrollverantwortlicher",
    auditor: "Auditor",
    dpo: "Datenschutzbeauftragter",
    process_owner: "Prozessverantwortlicher",
    viewer: "Betrachter",
  },
  en: {
    admin: "Administrator",
    risk_manager: "Risk Manager",
    control_owner: "Control Owner",
    auditor: "Auditor",
    dpo: "Data Protection Officer",
    process_owner: "Process Owner",
    viewer: "Viewer",
  },
};

const translations = {
  de: {
    preview: "Einladung zu ARCTOS",
    heading: "Sie wurden eingeladen",
    greeting: "Guten Tag,",
    intro: (inviter: string, org: string) =>
      `${inviter} hat Sie eingeladen, der Organisation "${org}" auf der ARCTOS GRC-Plattform beizutreten.`,
    role: "Ihre Rolle",
    organization: "Organisation",
    whatIsArctos: "Was ist ARCTOS?",
    arktosDescription:
      "ARCTOS ist eine integrierte Plattform für Governance, Risk & Compliance. Sie erhalten Zugriff auf Risikomanagement, Compliance-Tracking, Audit-Funktionen und mehr.",
    cta: "Einladung annehmen",
    expiry:
      "Dieser Einladungslink ist 7 Tage gültig. Sollte der Link abgelaufen sein, wenden Sie sich bitte an Ihren Administrator.",
    footer:
      "Diese E-Mail wurde automatisch von ARCTOS generiert. Bitte antworten Sie nicht auf diese E-Mail.",
  },
  en: {
    preview: "Invitation to ARCTOS",
    heading: "You have been invited",
    greeting: "Hello,",
    intro: (inviter: string, org: string) =>
      `${inviter} has invited you to join the organization "${org}" on the ARCTOS GRC platform.`,
    role: "Your Role",
    organization: "Organization",
    whatIsArctos: "What is ARCTOS?",
    arktosDescription:
      "ARCTOS is an integrated Governance, Risk & Compliance platform. You will get access to risk management, compliance tracking, audit capabilities, and more.",
    cta: "Accept Invitation",
    expiry:
      "This invitation link is valid for 7 days. If the link has expired, please contact your administrator.",
    footer:
      "This email was automatically generated by ARCTOS. Please do not reply to this email.",
  },
};

export function getSubject(
  _data: Record<string, unknown>,
  lang: "de" | "en"
): string {
  return lang === "de" ? "Einladung zu ARCTOS" : "Invitation to ARCTOS";
}

export const UserInvited: React.FC<UserInvitedProps> = ({
  lang,
  orgName,
  roleName,
  inviterName,
  acceptUrl,
}) => {
  const t = translations[lang];
  const roleLabel = roleLabels[lang][roleName] || roleName;

  return (
    <Html lang={lang}>
      <Head>
        <Font
          fontFamily="Arial"
          fallbackFontFamily="Helvetica"
          fontWeight={400}
          fontStyle="normal"
        />
      </Head>
      <Preview>{t.preview}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          {/* Header */}
          <Section style={styles.header}>
            <Text style={styles.logo}>ARCTOS</Text>
            <Text style={styles.logoSubtitle}>
              Audit, Risk, Compliance &amp; Trust
            </Text>
          </Section>

          <Hr style={styles.hr} />

          {/* Content */}
          <Section style={styles.content}>
            <Text style={styles.heading}>{t.heading}</Text>
            <Text style={styles.text}>{t.greeting}</Text>
            <Text style={styles.text}>
              {t.intro(inviterName, orgName)}
            </Text>

            <Section style={styles.card}>
              <Text style={styles.cardLabel}>{t.organization}</Text>
              <Text style={styles.cardValue}>{orgName}</Text>

              <Text style={styles.cardLabel}>{t.role}</Text>
              <Text style={styles.roleBadge}>{roleLabel}</Text>
            </Section>

            <Section style={styles.ctaSection}>
              <Button style={styles.button} href={acceptUrl}>
                {t.cta}
              </Button>
            </Section>

            <Section style={styles.infoSection}>
              <Text style={styles.infoHeading}>{t.whatIsArctos}</Text>
              <Text style={styles.infoText}>{t.arktosDescription}</Text>
            </Section>

            <Text style={styles.expiryText}>{t.expiry}</Text>
          </Section>

          <Hr style={styles.hr} />

          {/* Footer */}
          <Section style={styles.footer}>
            <Text style={styles.footerText}>{t.footer}</Text>
            <Text style={styles.footerBrand}>
              ARCTOS GRC Platform
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

const styles = {
  body: {
    backgroundColor: "#f4f4f5",
    fontFamily: "Arial, Helvetica, sans-serif",
    margin: "0" as const,
    padding: "0" as const,
  },
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    margin: "40px auto",
    maxWidth: "600px",
    overflow: "hidden" as const,
  },
  header: {
    backgroundColor: "#0f172a",
    padding: "24px 32px",
    textAlign: "center" as const,
  },
  logo: {
    color: "#ffffff",
    fontSize: "28px",
    fontWeight: "700" as const,
    letterSpacing: "3px",
    margin: "0",
  },
  logoSubtitle: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "4px 0 0 0",
    textTransform: "uppercase" as const,
  },
  hr: {
    borderColor: "#e4e4e7",
    borderTop: "1px solid #e4e4e7",
    margin: "0",
  },
  content: {
    padding: "32px",
  },
  heading: {
    color: "#0f172a",
    fontSize: "22px",
    fontWeight: "600" as const,
    margin: "0 0 16px 0",
  },
  text: {
    color: "#374151",
    fontSize: "15px",
    lineHeight: "24px",
    margin: "0 0 12px 0",
  },
  card: {
    backgroundColor: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    margin: "20px 0",
    padding: "20px",
  },
  cardLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "600" as const,
    letterSpacing: "0.5px",
    margin: "12px 0 2px 0",
    textTransform: "uppercase" as const,
  },
  cardValue: {
    color: "#0f172a",
    fontSize: "15px",
    fontWeight: "500" as const,
    margin: "0 0 8px 0",
  },
  roleBadge: {
    backgroundColor: "#2563eb",
    borderRadius: "4px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "13px",
    fontWeight: "600" as const,
    margin: "4px 0 0 0",
    padding: "4px 12px",
  },
  ctaSection: {
    margin: "24px 0",
    textAlign: "center" as const,
  },
  button: {
    backgroundColor: "#2563eb",
    borderRadius: "6px",
    color: "#ffffff",
    display: "inline-block" as const,
    fontSize: "16px",
    fontWeight: "600" as const,
    padding: "14px 40px",
    textDecoration: "none",
  },
  infoSection: {
    backgroundColor: "#f0f9ff",
    border: "1px solid #bae6fd",
    borderRadius: "6px",
    margin: "20px 0",
    padding: "16px",
  },
  infoHeading: {
    color: "#0c4a6e",
    fontSize: "14px",
    fontWeight: "600" as const,
    margin: "0 0 8px 0",
  },
  infoText: {
    color: "#0369a1",
    fontSize: "13px",
    lineHeight: "20px",
    margin: "0",
  },
  expiryText: {
    color: "#94a3b8",
    fontSize: "12px",
    fontStyle: "italic" as const,
    lineHeight: "18px",
    margin: "8px 0 0 0",
    textAlign: "center" as const,
  },
  footer: {
    padding: "20px 32px",
    textAlign: "center" as const,
  },
  footerText: {
    color: "#94a3b8",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "0 0 8px 0",
  },
  footerBrand: {
    color: "#94a3b8",
    fontSize: "11px",
    letterSpacing: "1px",
    margin: "0",
    textTransform: "uppercase" as const,
  },
};

export default UserInvited;
